//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 03:43:15 PM MSK
//

package io.rsug.zatupka.hmi;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.rsug.zatupka.hmi package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.rsug.zatupka.hmi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Instance }
     * 
     * @return
     *     the new instance of {@link Instance }
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     * @return
     *     the new instance of {@link Attribute }
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Value }
     * 
     * @return
     *     the new instance of {@link Value }
     */
    public Value createValue() {
        return new Value();
    }

}
