//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:30 PM MSK
//

package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ErrorLabels" form="unqualified">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Consumers" form="unqualified">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Runtimes" form="unqualified">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="RuntimeName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" form="unqualified"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *         <element name="PayloadInAlert" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *         <element name="RuntimeState" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *         <element name="RuleType" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *         <element name="BlockTime" type="{http://www.w3.org/2001/XMLSchema}integer" form="unqualified"/>
 *         <element name="SuppressionTime" type="{http://www.w3.org/2001/XMLSchema}integer" form="unqualified"/>
 *         <element name="HeaderRules" form="unqualified">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="UDSAttributes" form="unqualified">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="UDSAttribute" form="unqualified">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="Name" form="unqualified">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                             <element name="Operator" form="unqualified">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                             <element name="Value" form="unqualified">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorLabels",
    "consumers",
    "runtimes",
    "severity",
    "payloadInAlert",
    "runtimeState",
    "ruleType",
    "blockTime",
    "suppressionTime",
    "headerRules",
    "udsAttributes"
})
@XmlRootElement(name = "AlertRule")
public class AlertRule {

    @XmlElement(name = "ErrorLabels", required = true)
    protected AlertRule.ErrorLabels errorLabels;
    @XmlElement(name = "Consumers", required = true)
    protected AlertRule.Consumers consumers;
    @XmlElement(name = "Runtimes", required = true)
    protected AlertRule.Runtimes runtimes;
    @XmlElement(name = "Severity", required = true)
    protected String severity;
    @XmlElement(name = "PayloadInAlert", required = true)
    protected String payloadInAlert;
    @XmlElement(name = "RuntimeState", required = true)
    protected String runtimeState;
    @XmlElement(name = "RuleType", required = true)
    protected String ruleType;
    @XmlElement(name = "BlockTime", required = true)
    protected BigInteger blockTime;
    @XmlElement(name = "SuppressionTime", required = true)
    protected BigInteger suppressionTime;
    @XmlElement(name = "HeaderRules", required = true)
    protected AlertRule.HeaderRules headerRules;
    @XmlElement(name = "UDSAttributes", required = true)
    protected AlertRule.UDSAttributes udsAttributes;

    /**
     * Gets the value of the errorLabels property.
     * 
     * @return
     *     possible object is
     *     {@link AlertRule.ErrorLabels }
     *     
     */
    public AlertRule.ErrorLabels getErrorLabels() {
        return errorLabels;
    }

    /**
     * Sets the value of the errorLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertRule.ErrorLabels }
     *     
     */
    public void setErrorLabels(AlertRule.ErrorLabels value) {
        this.errorLabels = value;
    }

    /**
     * Gets the value of the consumers property.
     * 
     * @return
     *     possible object is
     *     {@link AlertRule.Consumers }
     *     
     */
    public AlertRule.Consumers getConsumers() {
        return consumers;
    }

    /**
     * Sets the value of the consumers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertRule.Consumers }
     *     
     */
    public void setConsumers(AlertRule.Consumers value) {
        this.consumers = value;
    }

    /**
     * Gets the value of the runtimes property.
     * 
     * @return
     *     possible object is
     *     {@link AlertRule.Runtimes }
     *     
     */
    public AlertRule.Runtimes getRuntimes() {
        return runtimes;
    }

    /**
     * Sets the value of the runtimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertRule.Runtimes }
     *     
     */
    public void setRuntimes(AlertRule.Runtimes value) {
        this.runtimes = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }

    /**
     * Gets the value of the payloadInAlert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayloadInAlert() {
        return payloadInAlert;
    }

    /**
     * Sets the value of the payloadInAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayloadInAlert(String value) {
        this.payloadInAlert = value;
    }

    /**
     * Gets the value of the runtimeState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuntimeState() {
        return runtimeState;
    }

    /**
     * Sets the value of the runtimeState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuntimeState(String value) {
        this.runtimeState = value;
    }

    /**
     * Gets the value of the ruleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * Sets the value of the ruleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleType(String value) {
        this.ruleType = value;
    }

    /**
     * Gets the value of the blockTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBlockTime() {
        return blockTime;
    }

    /**
     * Sets the value of the blockTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBlockTime(BigInteger value) {
        this.blockTime = value;
    }

    /**
     * Gets the value of the suppressionTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuppressionTime() {
        return suppressionTime;
    }

    /**
     * Sets the value of the suppressionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuppressionTime(BigInteger value) {
        this.suppressionTime = value;
    }

    /**
     * Gets the value of the headerRules property.
     * 
     * @return
     *     possible object is
     *     {@link AlertRule.HeaderRules }
     *     
     */
    public AlertRule.HeaderRules getHeaderRules() {
        return headerRules;
    }

    /**
     * Sets the value of the headerRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertRule.HeaderRules }
     *     
     */
    public void setHeaderRules(AlertRule.HeaderRules value) {
        this.headerRules = value;
    }

    /**
     * Gets the value of the udsAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AlertRule.UDSAttributes }
     *     
     */
    public AlertRule.UDSAttributes getUDSAttributes() {
        return udsAttributes;
    }

    /**
     * Sets the value of the udsAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertRule.UDSAttributes }
     *     
     */
    public void setUDSAttributes(AlertRule.UDSAttributes value) {
        this.udsAttributes = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Consumers {


    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ErrorLabels {


    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class HeaderRules {


    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="RuntimeName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" form="unqualified"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "runtimeName"
    })
    public static class Runtimes {

        @XmlElement(name = "RuntimeName", required = true)
        protected List<String> runtimeName;

        /**
         * Gets the value of the runtimeName property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore, any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the runtimeName property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getRuntimeName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * </p>
         * 
         * 
         * @return
         *     The value of the runtimeName property.
         */
        public List<String> getRuntimeName() {
            if (runtimeName == null) {
                runtimeName = new ArrayList<>();
            }
            return this.runtimeName;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="UDSAttribute" form="unqualified">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="Name" form="unqualified">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                   <element name="Operator" form="unqualified">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                   <element name="Value" form="unqualified">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "udsAttribute"
    })
    public static class UDSAttributes {

        @XmlElement(name = "UDSAttribute", required = true)
        protected AlertRule.UDSAttributes.UDSAttribute udsAttribute;

        /**
         * Gets the value of the udsAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link AlertRule.UDSAttributes.UDSAttribute }
         *     
         */
        public AlertRule.UDSAttributes.UDSAttribute getUDSAttribute() {
            return udsAttribute;
        }

        /**
         * Sets the value of the udsAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link AlertRule.UDSAttributes.UDSAttribute }
         *     
         */
        public void setUDSAttribute(AlertRule.UDSAttributes.UDSAttribute value) {
            this.udsAttribute = value;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="Name" form="unqualified">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *         <element name="Operator" form="unqualified">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *         <element name="Value" form="unqualified">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "operator",
            "value"
        })
        public static class UDSAttribute {

            @XmlElement(name = "Name", required = true)
            protected AlertRule.UDSAttributes.UDSAttribute.Name name;
            @XmlElement(name = "Operator", required = true)
            protected AlertRule.UDSAttributes.UDSAttribute.Operator operator;
            @XmlElement(name = "Value", required = true)
            protected AlertRule.UDSAttributes.UDSAttribute.Value value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link AlertRule.UDSAttributes.UDSAttribute.Name }
             *     
             */
            public AlertRule.UDSAttributes.UDSAttribute.Name getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link AlertRule.UDSAttributes.UDSAttribute.Name }
             *     
             */
            public void setName(AlertRule.UDSAttributes.UDSAttribute.Name value) {
                this.name = value;
            }

            /**
             * Gets the value of the operator property.
             * 
             * @return
             *     possible object is
             *     {@link AlertRule.UDSAttributes.UDSAttribute.Operator }
             *     
             */
            public AlertRule.UDSAttributes.UDSAttribute.Operator getOperator() {
                return operator;
            }

            /**
             * Sets the value of the operator property.
             * 
             * @param value
             *     allowed object is
             *     {@link AlertRule.UDSAttributes.UDSAttribute.Operator }
             *     
             */
            public void setOperator(AlertRule.UDSAttributes.UDSAttribute.Operator value) {
                this.operator = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link AlertRule.UDSAttributes.UDSAttribute.Value }
             *     
             */
            public AlertRule.UDSAttributes.UDSAttribute.Value getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link AlertRule.UDSAttributes.UDSAttribute.Value }
             *     
             */
            public void setValue(AlertRule.UDSAttributes.UDSAttribute.Value value) {
                this.value = value;
            }


            /**
             * <p>Java class for anonymous complex type</p>.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.</p>
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Name {


            }


            /**
             * <p>Java class for anonymous complex type</p>.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.</p>
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Operator {


            }


            /**
             * <p>Java class for anonymous complex type</p>.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.</p>
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Value {


            }

        }

    }

}
