//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:24:20 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}AdapterTypeData" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adapterTypeData"
})
@XmlRootElement(name = "AllInOneAttributes")
public class AllInOneAttributes {

    @XmlElement(name = "AdapterTypeData")
    protected AdapterTypeData adapterTypeData;

    /**
     * Gets the value of the adapterTypeData property.
     * 
     * @return
     *     possible object is
     *     {@link AdapterTypeData }
     *     
     */
    public AdapterTypeData getAdapterTypeData() {
        return adapterTypeData;
    }

    /**
     * Sets the value of the adapterTypeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdapterTypeData }
     *     
     */
    public void setAdapterTypeData(AdapterTypeData value) {
        this.adapterTypeData = value;
    }

}
