//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:24:20 PM MSK
//

package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}SenderConnectivity"/>
 *         <element ref="{}NamespaceMapping"/>
 *         <element ref="{}NoReceiverBehaviour" minOccurs="0"/>
 *         <element ref="{}ReceiverConfigurations"/>
 *         <element ref="{}ReceiverAssignmentList" minOccurs="0"/>
 *         <element ref="{}DynamicalRouting" minOccurs="0"/>
 *         <element ref="{}ReceiverConnectivityList"/>
 *         <element ref="{}Conditions"/>
 *         <element ref="{}ScenarioConfiguration" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "senderConnectivity",
    "namespaceMapping",
    "noReceiverBehaviour",
    "receiverConfigurations",
    "receiverAssignmentList",
    "dynamicalRouting",
    "receiverConnectivityList",
    "conditions",
    "scenarioConfiguration"
})
@XmlRootElement(name = "AllInOne")
public class AllInOne {

    @XmlElement(name = "SenderConnectivity", required = true)
    protected SenderConnectivity senderConnectivity;
    @XmlElement(name = "NamespaceMapping", required = true)
    protected NamespaceMapping namespaceMapping;
    @XmlElement(name = "NoReceiverBehaviour")
    protected NoReceiverBehaviour noReceiverBehaviour;
    @XmlElement(name = "ReceiverConfigurations", required = true)
    protected ReceiverConfigurations receiverConfigurations;
    @XmlElement(name = "ReceiverAssignmentList")
    protected ReceiverAssignmentList receiverAssignmentList;
    @XmlElement(name = "DynamicalRouting")
    protected DynamicalRouting dynamicalRouting;
    @XmlElement(name = "ReceiverConnectivityList", required = true)
    protected ReceiverConnectivityList receiverConnectivityList;
    @XmlElement(name = "Conditions", required = true)
    protected Conditions conditions;
    @XmlElement(name = "ScenarioConfiguration")
    protected ScenarioConfiguration scenarioConfiguration;
    @XmlAttribute(name = "version", required = true)
    protected BigInteger version;

    /**
     * Gets the value of the senderConnectivity property.
     * 
     * @return
     *     possible object is
     *     {@link SenderConnectivity }
     *     
     */
    public SenderConnectivity getSenderConnectivity() {
        return senderConnectivity;
    }

    /**
     * Sets the value of the senderConnectivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderConnectivity }
     *     
     */
    public void setSenderConnectivity(SenderConnectivity value) {
        this.senderConnectivity = value;
    }

    /**
     * Gets the value of the namespaceMapping property.
     * 
     * @return
     *     possible object is
     *     {@link NamespaceMapping }
     *     
     */
    public NamespaceMapping getNamespaceMapping() {
        return namespaceMapping;
    }

    /**
     * Sets the value of the namespaceMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespaceMapping }
     *     
     */
    public void setNamespaceMapping(NamespaceMapping value) {
        this.namespaceMapping = value;
    }

    /**
     * Gets the value of the noReceiverBehaviour property.
     * 
     * @return
     *     possible object is
     *     {@link NoReceiverBehaviour }
     *     
     */
    public NoReceiverBehaviour getNoReceiverBehaviour() {
        return noReceiverBehaviour;
    }

    /**
     * Sets the value of the noReceiverBehaviour property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoReceiverBehaviour }
     *     
     */
    public void setNoReceiverBehaviour(NoReceiverBehaviour value) {
        this.noReceiverBehaviour = value;
    }

    /**
     * Gets the value of the receiverConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverConfigurations }
     *     
     */
    public ReceiverConfigurations getReceiverConfigurations() {
        return receiverConfigurations;
    }

    /**
     * Sets the value of the receiverConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverConfigurations }
     *     
     */
    public void setReceiverConfigurations(ReceiverConfigurations value) {
        this.receiverConfigurations = value;
    }

    /**
     * Gets the value of the receiverAssignmentList property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverAssignmentList }
     *     
     */
    public ReceiverAssignmentList getReceiverAssignmentList() {
        return receiverAssignmentList;
    }

    /**
     * Sets the value of the receiverAssignmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverAssignmentList }
     *     
     */
    public void setReceiverAssignmentList(ReceiverAssignmentList value) {
        this.receiverAssignmentList = value;
    }

    /**
     * Gets the value of the dynamicalRouting property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicalRouting }
     *     
     */
    public DynamicalRouting getDynamicalRouting() {
        return dynamicalRouting;
    }

    /**
     * Sets the value of the dynamicalRouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicalRouting }
     *     
     */
    public void setDynamicalRouting(DynamicalRouting value) {
        this.dynamicalRouting = value;
    }

    /**
     * Gets the value of the receiverConnectivityList property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverConnectivityList }
     *     
     */
    public ReceiverConnectivityList getReceiverConnectivityList() {
        return receiverConnectivityList;
    }

    /**
     * Sets the value of the receiverConnectivityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverConnectivityList }
     *     
     */
    public void setReceiverConnectivityList(ReceiverConnectivityList value) {
        this.receiverConnectivityList = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the scenarioConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link ScenarioConfiguration }
     *     
     */
    public ScenarioConfiguration getScenarioConfiguration() {
        return scenarioConfiguration;
    }

    /**
     * Sets the value of the scenarioConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScenarioConfiguration }
     *     
     */
    public void setScenarioConfiguration(ScenarioConfiguration value) {
        this.scenarioConfiguration = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

}
