//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for CONDLINE_COMPOP_ENUM</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CONDLINE_COMPOP_ENUM">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="EX"/>
 *     <enumeration value="EQ"/>
 *     <enumeration value="NE"/>
 *     <enumeration value="CP"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CONDLINE_COMPOP_ENUM")
@XmlEnum
public enum CONDLINECOMPOPENUM {

    EX,
    EQ,
    NE,
    CP;

    public String value() {
        return name();
    }

    public static CONDLINECOMPOPENUM fromValue(String v) {
        return valueOf(v);
    }

}
