//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}COMPGROUP"/>
 *         <element ref="{}COUNTER"/>
 *         <element name="COMPOP" type="{}CONDLINE_COMPOP_ENUM"/>
 *         <element ref="{}LEXTRACTOR"/>
 *         <element ref="{}REXTRACTOR"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "compgroup",
    "counter",
    "compop",
    "lextractor",
    "rextractor"
})
@XmlRootElement(name = "CONDLINE")
public class CONDLINE {

    @XmlElement(name = "COMPGROUP", required = true)
    protected BigInteger compgroup;
    @XmlElement(name = "COUNTER", required = true)
    protected BigInteger counter;
    @XmlElement(name = "COMPOP", required = true)
    @XmlSchemaType(name = "string")
    protected CONDLINECOMPOPENUM compop;
    @XmlElement(name = "LEXTRACTOR", required = true)
    protected TRDEXTRACTORT lextractor;
    @XmlElement(name = "REXTRACTOR", required = true)
    protected TRDEXTRACTORT rextractor;

    /**
     * Gets the value of the compgroup property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOMPGROUP() {
        return compgroup;
    }

    /**
     * Sets the value of the compgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOMPGROUP(BigInteger value) {
        this.compgroup = value;
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOUNTER() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOUNTER(BigInteger value) {
        this.counter = value;
    }

    /**
     * Gets the value of the compop property.
     * 
     * @return
     *     possible object is
     *     {@link CONDLINECOMPOPENUM }
     *     
     */
    public CONDLINECOMPOPENUM getCOMPOP() {
        return compop;
    }

    /**
     * Sets the value of the compop property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONDLINECOMPOPENUM }
     *     
     */
    public void setCOMPOP(CONDLINECOMPOPENUM value) {
        this.compop = value;
    }

    /**
     * Gets the value of the lextractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getLEXTRACTOR() {
        return lextractor;
    }

    /**
     * Sets the value of the lextractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setLEXTRACTOR(TRDEXTRACTORT value) {
        this.lextractor = value;
    }

    /**
     * Gets the value of the rextractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getREXTRACTOR() {
        return rextractor;
    }

    /**
     * Sets the value of the rextractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setREXTRACTOR(TRDEXTRACTORT value) {
        this.rextractor = value;
    }

}
