//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.17 at 07:35:23 PM MSK 
//


package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}COMPGROUP"/>
 *         &lt;element ref="{}COUNTER"/>
 *         &lt;element ref="{}COMPOP"/>
 *         &lt;element ref="{}LEXTRACTOR"/>
 *         &lt;element ref="{}REXTRACTOR"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "compgroup",
    "counter",
    "compop",
    "lextractor",
    "rextractor"
})
@XmlRootElement(name = "CONDLINE")
public class CONDLINE {

    @XmlElement(name = "COMPGROUP", required = true)
    protected BigInteger compgroup;
    @XmlElement(name = "COUNTER", required = true)
    protected BigInteger counter;
    @XmlElement(name = "COMPOP", required = true)
    @XmlSchemaType(name = "string")
    protected CONDLINECOMPOPENUM compop;
    @XmlElement(name = "LEXTRACTOR", required = true)
    protected TRDEXTRACTORT lextractor;
    @XmlElement(name = "REXTRACTOR", required = true)
    protected TRDEXTRACTORT rextractor;

    /**
     * Gets the value of the compgroup property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOMPGROUP() {
        return compgroup;
    }

    /**
     * Sets the value of the compgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOMPGROUP(BigInteger value) {
        this.compgroup = value;
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOUNTER() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOUNTER(BigInteger value) {
        this.counter = value;
    }

    /**
     * Gets the value of the compop property.
     * 
     * @return
     *     possible object is
     *     {@link CONDLINECOMPOPENUM }
     *     
     */
    public CONDLINECOMPOPENUM getCOMPOP() {
        return compop;
    }

    /**
     * Sets the value of the compop property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONDLINECOMPOPENUM }
     *     
     */
    public void setCOMPOP(CONDLINECOMPOPENUM value) {
        this.compop = value;
    }

    /**
     * Gets the value of the lextractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getLEXTRACTOR() {
        return lextractor;
    }

    /**
     * Sets the value of the lextractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setLEXTRACTOR(TRDEXTRACTORT value) {
        this.lextractor = value;
    }

    /**
     * Gets the value of the rextractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getREXTRACTOR() {
        return rextractor;
    }

    /**
     * Sets the value of the rextractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setREXTRACTOR(TRDEXTRACTORT value) {
        this.rextractor = value;
    }

}
