//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}RDS_CONDSHORT"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rdscondshort"
})
@XmlRootElement(name = "Condition")
public class Condition {

    @XmlElement(name = "RDS_CONDSHORT", required = true)
    protected RDSCONDSHORT rdscondshort;

    /**
     * Gets the value of the rdscondshort property.
     * 
     * @return
     *     possible object is
     *     {@link RDSCONDSHORT }
     *     
     */
    public RDSCONDSHORT getRDSCONDSHORT() {
        return rdscondshort;
    }

    /**
     * Sets the value of the rdscondshort property.
     * 
     * @param value
     *     allowed object is
     *     {@link RDSCONDSHORT }
     *     
     */
    public void setRDSCONDSHORT(RDSCONDSHORT value) {
        this.rdscondshort = value;
    }

}
