//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:24:20 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}ExtractorId"/>
 *         <element ref="{}ExtractorData"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extractorId",
    "extractorData"
})
@XmlRootElement(name = "Extractor")
public class Extractor {

    @XmlElement(name = "ExtractorId", required = true)
    protected String extractorId;
    @XmlElement(name = "ExtractorData", required = true)
    protected TRDEXTRACTORT extractorData;

    /**
     * Gets the value of the extractorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtractorId() {
        return extractorId;
    }

    /**
     * Sets the value of the extractorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtractorId(String value) {
        this.extractorId = value;
    }

    /**
     * Gets the value of the extractorData property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getExtractorData() {
        return extractorData;
    }

    /**
     * Sets the value of the extractorData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setExtractorData(TRDEXTRACTORT value) {
        this.extractorData = value;
    }

}
