//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.08 at 08:01:28 AM MSK 
//


package io.rsug.zatupka.allinone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ExtractorId"/>
 *         &lt;element ref="{}ExtractorData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extractorId",
    "extractorData"
})
@XmlRootElement(name = "Extractor")
public class Extractor {

    @XmlElement(name = "ExtractorId", required = true)
    protected String extractorId;
    @XmlElement(name = "ExtractorData", required = true)
    protected TRDEXTRACTORT extractorData;

    /**
     * Gets the value of the extractorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtractorId() {
        return extractorId;
    }

    /**
     * Sets the value of the extractorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtractorId(String value) {
        this.extractorId = value;
    }

    /**
     * Gets the value of the extractorData property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getExtractorData() {
        return extractorData;
    }

    /**
     * Sets the value of the extractorData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setExtractorData(TRDEXTRACTORT value) {
        this.extractorData = value;
    }

}
