//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:30 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}FieldMapping"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldMapping"
})
@XmlRootElement(name = "HeaderMapping")
public class HeaderMapping {

    @XmlElement(name = "FieldMapping", required = true)
    protected FieldMapping fieldMapping;

    /**
     * Gets the value of the fieldMapping property.
     * 
     * @return
     *     possible object is
     *     {@link FieldMapping }
     *     
     */
    public FieldMapping getFieldMapping() {
        return fieldMapping;
    }

    /**
     * Sets the value of the fieldMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldMapping }
     *     
     */
    public void setFieldMapping(FieldMapping value) {
        this.fieldMapping = value;
    }

}
