//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.08 at 08:01:28 AM MSK 
//


package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}InterfaceConditionId"/>
 *         &lt;element ref="{}Interfaces"/>
 *         &lt;element ref="{}Counter"/>
 *         &lt;element ref="{}Operation"/>
 *         &lt;element ref="{}MappingRequired"/>
 *         &lt;element ref="{}Condition" minOccurs="0"/>
 *         &lt;element ref="{}SplitItems"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interfaceConditionId",
    "interfaces",
    "counter",
    "operation",
    "mappingRequired",
    "condition",
    "splitItems"
})
@XmlRootElement(name = "InterfaceDetermination")
public class InterfaceDetermination {

    @XmlElement(name = "InterfaceConditionId", required = true)
    protected String interfaceConditionId;
    @XmlElement(name = "Interfaces", required = true)
    protected Interfaces interfaces;
    @XmlElement(name = "Counter", required = true)
    protected BigInteger counter;
    @XmlElement(name = "Operation", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String operation;
    @XmlElement(name = "MappingRequired", required = true)
    protected BigInteger mappingRequired;
    @XmlElement(name = "Condition")
    protected Condition condition;
    @XmlElement(name = "SplitItems", required = true)
    protected SplitItems splitItems;

    /**
     * Gets the value of the interfaceConditionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceConditionId() {
        return interfaceConditionId;
    }

    /**
     * Sets the value of the interfaceConditionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceConditionId(String value) {
        this.interfaceConditionId = value;
    }

    /**
     * Gets the value of the interfaces property.
     * 
     * @return
     *     possible object is
     *     {@link Interfaces }
     *     
     */
    public Interfaces getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interfaces }
     *     
     */
    public void setInterfaces(Interfaces value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCounter() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCounter(BigInteger value) {
        this.counter = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the mappingRequired property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMappingRequired() {
        return mappingRequired;
    }

    /**
     * Sets the value of the mappingRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMappingRequired(BigInteger value) {
        this.mappingRequired = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link Condition }
     *     
     */
    public Condition getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Condition }
     *     
     */
    public void setCondition(Condition value) {
        this.condition = value;
    }

    /**
     * Gets the value of the splitItems property.
     * 
     * @return
     *     possible object is
     *     {@link SplitItems }
     *     
     */
    public SplitItems getSplitItems() {
        return splitItems;
    }

    /**
     * Sets the value of the splitItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitItems }
     *     
     */
    public void setSplitItems(SplitItems value) {
        this.splitItems = value;
    }

}
