//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.11 at 05:39:49 PM MSK 
//


package io.rsug.zatupka.allinone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://sap.com/xi/ib/prefix}NSM"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nsm"
})
@XmlRootElement(name = "NamespaceMapping")
public class NamespaceMapping {

    @XmlElement(name = "NSM", namespace = "http://sap.com/xi/ib/prefix", required = true)
    protected NSM nsm;

    /**
     * Gets the value of the nsm property.
     * 
     * @return
     *     possible object is
     *     {@link NSM }
     *     
     */
    public NSM getNSM() {
        return nsm;
    }

    /**
     * Sets the value of the nsm property.
     * 
     * @param value
     *     allowed object is
     *     {@link NSM }
     *     
     */
    public void setNSM(NSM value) {
        this.nsm = value;
    }

}
