//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://sap.com/xi/ib/prefix}NSM"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nsm"
})
@XmlRootElement(name = "NamespaceMapping")
public class NamespaceMapping {

    @XmlElement(name = "NSM", namespace = "http://sap.com/xi/ib/prefix", required = true)
    protected NSM nsm;

    /**
     * Gets the value of the nsm property.
     * 
     * @return
     *     possible object is
     *     {@link NSM }
     *     
     */
    public NSM getNSM() {
        return nsm;
    }

    /**
     * Sets the value of the nsm property.
     * 
     * @param value
     *     allowed object is
     *     {@link NSM }
     *     
     */
    public void setNSM(NSM value) {
        this.nsm = value;
    }

}
