//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.19 at 06:20:59 PM MSK 
//


package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IfNoReceiverFound"/>
 *         &lt;element ref="{}DefaultReceiverId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ifNoReceiverFound",
    "defaultReceiverId"
})
@XmlRootElement(name = "NoReceiverBehaviour")
public class NoReceiverBehaviour {

    @XmlElement(name = "IfNoReceiverFound", required = true)
    protected BigInteger ifNoReceiverFound;
    @XmlElement(name = "DefaultReceiverId")
    protected String defaultReceiverId;

    /**
     * Gets the value of the ifNoReceiverFound property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIfNoReceiverFound() {
        return ifNoReceiverFound;
    }

    /**
     * Sets the value of the ifNoReceiverFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIfNoReceiverFound(BigInteger value) {
        this.ifNoReceiverFound = value;
    }

    /**
     * Gets the value of the defaultReceiverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultReceiverId() {
        return defaultReceiverId;
    }

    /**
     * Sets the value of the defaultReceiverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultReceiverId(String value) {
        this.defaultReceiverId = value;
    }

}
