//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}IfNoReceiverFound"/>
 *         <element ref="{}DefaultReceiverId" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ifNoReceiverFound",
    "defaultReceiverId"
})
@XmlRootElement(name = "NoReceiverBehaviour")
public class NoReceiverBehaviour {

    @XmlElement(name = "IfNoReceiverFound", required = true)
    protected BigInteger ifNoReceiverFound;
    @XmlElement(name = "DefaultReceiverId")
    protected String defaultReceiverId;

    /**
     * Gets the value of the ifNoReceiverFound property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIfNoReceiverFound() {
        return ifNoReceiverFound;
    }

    /**
     * Sets the value of the ifNoReceiverFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIfNoReceiverFound(BigInteger value) {
        this.ifNoReceiverFound = value;
    }

    /**
     * Gets the value of the defaultReceiverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultReceiverId() {
        return defaultReceiverId;
    }

    /**
     * Sets the value of the defaultReceiverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultReceiverId(String value) {
        this.defaultReceiverId = value;
    }

}
