//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.08 at 08:01:28 AM MSK 
//


package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.rsug.zatupka.allinone package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CONDITIONID_QNAME = new QName("", "CONDITIONID");
    private final static QName _IfNoReceiverFound_QNAME = new QName("", "IfNoReceiverFound");
    private final static QName _ReceiverId_QNAME = new QName("", "ReceiverId");
    private final static QName _COMPGROUP_QNAME = new QName("", "COMPGROUP");
    private final static QName _DefaultReceiverId_QNAME = new QName("", "DefaultReceiverId");
    private final static QName _InterfaceNamespace_QNAME = new QName("", "InterfaceNamespace");
    private final static QName _VALUE_QNAME = new QName("", "VALUE");
    private final static QName _ValidationMode_QNAME = new QName("", "ValidationMode");
    private final static QName _Operation_QNAME = new QName("", "Operation");
    private final static QName _PartySchemaExtractor_QNAME = new QName("", "PartySchemaExtractor");
    private final static QName _MappingRequired_QNAME = new QName("", "MappingRequired");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _Counter_QNAME = new QName("", "Counter");
    private final static QName _ReceiverConditionId_QNAME = new QName("", "ReceiverConditionId");
    private final static QName _EXTRACTORID_QNAME = new QName("", "EXTRACTORID");
    private final static QName _InterfaceName_QNAME = new QName("", "InterfaceName");
    private final static QName _TYPE_QNAME = new QName("", "TYPE");
    private final static QName _ExtractorData_QNAME = new QName("", "ExtractorData");
    private final static QName _COMPOP_QNAME = new QName("", "COMPOP");
    private final static QName _ServiceExtractor_QNAME = new QName("", "ServiceExtractor");
    private final static QName _ExtractorId_QNAME = new QName("", "ExtractorId");
    private final static QName _UseGlobal_QNAME = new QName("", "UseGlobal");
    private final static QName _LEXTRACTOR_QNAME = new QName("", "LEXTRACTOR");
    private final static QName _COBJNAME_QNAME = new QName("", "COBJNAME");
    private final static QName _SplitCounter_QNAME = new QName("", "SplitCounter");
    private final static QName _InterfaceConditionId_QNAME = new QName("", "InterfaceConditionId");
    private final static QName _DATATYPE_QNAME = new QName("", "DATATYPE");
    private final static QName _COBJNS_QNAME = new QName("", "COBJNS");
    private final static QName _ReceiverConnectivityId_QNAME = new QName("", "ReceiverConnectivityId");
    private final static QName _VirusScanMode_QNAME = new QName("", "VirusScanMode");
    private final static QName _Value_QNAME = new QName("", "Value");
    private final static QName _PartyExtractor_QNAME = new QName("", "PartyExtractor");
    private final static QName _PartyAgencyExtractor_QNAME = new QName("", "PartyAgencyExtractor");
    private final static QName _QualityOfService_QNAME = new QName("", "QualityOfService");
    private final static QName _MULTLINE_QNAME = new QName("", "MULTLINE");
    private final static QName _COUNTER_QNAME = new QName("", "COUNTER");
    private final static QName _REXTRACTOR_QNAME = new QName("", "REXTRACTOR");
    private final static QName _ReceiverIds_QNAME = new QName("", "ReceiverIds");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.rsug.zatupka.allinone
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NSM }
     * 
     */
    public NSM createNSM() {
        return new NSM();
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinition() {
        return new Definition();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link TRDEXTRACTORT }
     * 
     */
    public TRDEXTRACTORT createTRDEXTRACTORT() {
        return new TRDEXTRACTORT();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link RDSCONDSHORT }
     * 
     */
    public RDSCONDSHORT createRDSCONDSHORT() {
        return new RDSCONDSHORT();
    }

    /**
     * Create an instance of {@link CONDLINE }
     * 
     */
    public CONDLINE createCONDLINE() {
        return new CONDLINE();
    }

    /**
     * Create an instance of {@link AdapterTypeData }
     * 
     */
    public AdapterTypeData createAdapterTypeData() {
        return new AdapterTypeData();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Namespace }
     * 
     */
    public Namespace createNamespace() {
        return new Namespace();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ReceiverConnectivityList }
     * 
     */
    public ReceiverConnectivityList createReceiverConnectivityList() {
        return new ReceiverConnectivityList();
    }

    /**
     * Create an instance of {@link ReceiverConnectivity }
     * 
     */
    public ReceiverConnectivity createReceiverConnectivity() {
        return new ReceiverConnectivity();
    }

    /**
     * Create an instance of {@link AllInOneAttributes }
     * 
     */
    public AllInOneAttributes createAllInOneAttributes() {
        return new AllInOneAttributes();
    }

    /**
     * Create an instance of {@link HeaderMapping }
     * 
     */
    public HeaderMapping createHeaderMapping() {
        return new HeaderMapping();
    }

    /**
     * Create an instance of {@link FieldMapping }
     * 
     */
    public FieldMapping createFieldMapping() {
        return new FieldMapping();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Extractor }
     * 
     */
    public Extractor createExtractor() {
        return new Extractor();
    }

    /**
     * Create an instance of {@link Receiver }
     * 
     */
    public Receiver createReceiver() {
        return new Receiver();
    }

    /**
     * Create an instance of {@link SplitItem }
     * 
     */
    public SplitItem createSplitItem() {
        return new SplitItem();
    }

    /**
     * Create an instance of {@link Multiplicity }
     * 
     */
    public Multiplicity createMultiplicity() {
        return new Multiplicity();
    }

    /**
     * Create an instance of {@link SplitItems }
     * 
     */
    public SplitItems createSplitItems() {
        return new SplitItems();
    }

    /**
     * Create an instance of {@link ReceiverAssignment }
     * 
     */
    public ReceiverAssignment createReceiverAssignment() {
        return new ReceiverAssignment();
    }

    /**
     * Create an instance of {@link ReceiverId }
     * 
     */
    public ReceiverId createReceiverId() {
        return new ReceiverId();
    }

    /**
     * Create an instance of {@link InterfaceDeterminations }
     * 
     */
    public InterfaceDeterminations createInterfaceDeterminations() {
        return new InterfaceDeterminations();
    }

    /**
     * Create an instance of {@link InterfaceDetermination }
     * 
     */
    public InterfaceDetermination createInterfaceDetermination() {
        return new InterfaceDetermination();
    }

    /**
     * Create an instance of {@link Interfaces }
     * 
     */
    public Interfaces createInterfaces() {
        return new Interfaces();
    }

    /**
     * Create an instance of {@link Interface }
     * 
     */
    public Interface createInterface() {
        return new Interface();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link ScenarioConfiguration }
     * 
     */
    public ScenarioConfiguration createScenarioConfiguration() {
        return new ScenarioConfiguration();
    }

    /**
     * Create an instance of {@link NamespaceMapping }
     * 
     */
    public NamespaceMapping createNamespaceMapping() {
        return new NamespaceMapping();
    }

    /**
     * Create an instance of {@link ReceiverConfigurations }
     * 
     */
    public ReceiverConfigurations createReceiverConfigurations() {
        return new ReceiverConfigurations();
    }

    /**
     * Create an instance of {@link ReceiverConfiguration }
     * 
     */
    public ReceiverConfiguration createReceiverConfiguration() {
        return new ReceiverConfiguration();
    }

    /**
     * Create an instance of {@link AllInOne }
     * 
     */
    public AllInOne createAllInOne() {
        return new AllInOne();
    }

    /**
     * Create an instance of {@link SenderConnectivity }
     * 
     */
    public SenderConnectivity createSenderConnectivity() {
        return new SenderConnectivity();
    }

    /**
     * Create an instance of {@link NoReceiverBehaviour }
     * 
     */
    public NoReceiverBehaviour createNoReceiverBehaviour() {
        return new NoReceiverBehaviour();
    }

    /**
     * Create an instance of {@link ReceiverAssignmentList }
     * 
     */
    public ReceiverAssignmentList createReceiverAssignmentList() {
        return new ReceiverAssignmentList();
    }

    /**
     * Create an instance of {@link TRDEXTRACTOR }
     * 
     */
    public TRDEXTRACTOR createTRDEXTRACTOR() {
        return new TRDEXTRACTOR();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONDITIONID")
    public JAXBElement<String> createCONDITIONID(String value) {
        return new JAXBElement<String>(_CONDITIONID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IfNoReceiverFound")
    public JAXBElement<BigInteger> createIfNoReceiverFound(BigInteger value) {
        return new JAXBElement<BigInteger>(_IfNoReceiverFound_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReceiverId")
    public JAXBElement<String> createReceiverId(String value) {
        return new JAXBElement<String>(_ReceiverId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPGROUP")
    public JAXBElement<BigInteger> createCOMPGROUP(BigInteger value) {
        return new JAXBElement<BigInteger>(_COMPGROUP_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DefaultReceiverId")
    public JAXBElement<String> createDefaultReceiverId(String value) {
        return new JAXBElement<String>(_DefaultReceiverId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InterfaceNamespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInterfaceNamespace(String value) {
        return new JAXBElement<String>(_InterfaceNamespace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VALUE")
    public JAXBElement<String> createVALUE(String value) {
        return new JAXBElement<String>(_VALUE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ValidationMode")
    public JAXBElement<BigInteger> createValidationMode(BigInteger value) {
        return new JAXBElement<BigInteger>(_ValidationMode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOperation(String value) {
        return new JAXBElement<String>(_Operation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartySchemaExtractor")
    public JAXBElement<TRDEXTRACTORT> createPartySchemaExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<TRDEXTRACTORT>(_PartySchemaExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MappingRequired")
    public JAXBElement<BigInteger> createMappingRequired(BigInteger value) {
        return new JAXBElement<BigInteger>(_MappingRequired_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Counter")
    public JAXBElement<BigInteger> createCounter(BigInteger value) {
        return new JAXBElement<BigInteger>(_Counter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReceiverConditionId")
    public JAXBElement<String> createReceiverConditionId(String value) {
        return new JAXBElement<String>(_ReceiverConditionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXTRACTORID")
    public JAXBElement<String> createEXTRACTORID(String value) {
        return new JAXBElement<String>(_EXTRACTORID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InterfaceName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInterfaceName(String value) {
        return new JAXBElement<String>(_InterfaceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTYPE(String value) {
        return new JAXBElement<String>(_TYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExtractorData")
    public JAXBElement<TRDEXTRACTORT> createExtractorData(TRDEXTRACTORT value) {
        return new JAXBElement<TRDEXTRACTORT>(_ExtractorData_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPOP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCOMPOP(String value) {
        return new JAXBElement<String>(_COMPOP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServiceExtractor")
    public JAXBElement<TRDEXTRACTORT> createServiceExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<TRDEXTRACTORT>(_ServiceExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExtractorId")
    public JAXBElement<String> createExtractorId(String value) {
        return new JAXBElement<String>(_ExtractorId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UseGlobal")
    public JAXBElement<Boolean> createUseGlobal(Boolean value) {
        return new JAXBElement<Boolean>(_UseGlobal_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEXTRACTOR")
    public JAXBElement<TRDEXTRACTORT> createLEXTRACTOR(TRDEXTRACTORT value) {
        return new JAXBElement<TRDEXTRACTORT>(_LEXTRACTOR_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COBJNAME")
    public JAXBElement<String> createCOBJNAME(String value) {
        return new JAXBElement<String>(_COBJNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SplitCounter")
    public JAXBElement<BigInteger> createSplitCounter(BigInteger value) {
        return new JAXBElement<BigInteger>(_SplitCounter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InterfaceConditionId")
    public JAXBElement<String> createInterfaceConditionId(String value) {
        return new JAXBElement<String>(_InterfaceConditionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATATYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDATATYPE(String value) {
        return new JAXBElement<String>(_DATATYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COBJNS")
    public JAXBElement<String> createCOBJNS(String value) {
        return new JAXBElement<String>(_COBJNS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReceiverConnectivityId")
    public JAXBElement<String> createReceiverConnectivityId(String value) {
        return new JAXBElement<String>(_ReceiverConnectivityId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VirusScanMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVirusScanMode(String value) {
        return new JAXBElement<String>(_VirusScanMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartyExtractor")
    public JAXBElement<TRDEXTRACTORT> createPartyExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<TRDEXTRACTORT>(_PartyExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartyAgencyExtractor")
    public JAXBElement<TRDEXTRACTORT> createPartyAgencyExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<TRDEXTRACTORT>(_PartyAgencyExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QualityOfService")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createQualityOfService(String value) {
        return new JAXBElement<String>(_QualityOfService_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MULTLINE")
    public JAXBElement<String> createMULTLINE(String value) {
        return new JAXBElement<String>(_MULTLINE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COUNTER")
    public JAXBElement<BigInteger> createCOUNTER(BigInteger value) {
        return new JAXBElement<BigInteger>(_COUNTER_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REXTRACTOR")
    public JAXBElement<TRDEXTRACTORT> createREXTRACTOR(TRDEXTRACTORT value) {
        return new JAXBElement<TRDEXTRACTORT>(_REXTRACTOR_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiverId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReceiverIds")
    public JAXBElement<ReceiverId> createReceiverIds(ReceiverId value) {
        return new JAXBElement<ReceiverId>(_ReceiverIds_QNAME, ReceiverId.class, null, value);
    }

}
