//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.rsug.zatupka.allinone package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ValidationMode_QNAME = new QName("", "ValidationMode");
    private static final QName _VirusScanMode_QNAME = new QName("", "VirusScanMode");
    private static final QName _Name_QNAME = new QName("", "Name");
    private static final QName _IfNoReceiverFound_QNAME = new QName("", "IfNoReceiverFound");
    private static final QName _DefaultReceiverId_QNAME = new QName("", "DefaultReceiverId");
    private static final QName _ReceiverId_QNAME = new QName("", "ReceiverId");
    private static final QName _PartyExtractor_QNAME = new QName("", "PartyExtractor");
    private static final QName _PartyAgencyExtractor_QNAME = new QName("", "PartyAgencyExtractor");
    private static final QName _PartySchemaExtractor_QNAME = new QName("", "PartySchemaExtractor");
    private static final QName _ServiceExtractor_QNAME = new QName("", "ServiceExtractor");
    private static final QName _QualityOfService_QNAME = new QName("", "QualityOfService");
    private static final QName _ReceiverConnectivityId_QNAME = new QName("", "ReceiverConnectivityId");
    private static final QName _InterfaceConditionId_QNAME = new QName("", "InterfaceConditionId");
    private static final QName _InterfaceName_QNAME = new QName("", "InterfaceName");
    private static final QName _InterfaceNamespace_QNAME = new QName("", "InterfaceNamespace");
    private static final QName _Counter_QNAME = new QName("", "Counter");
    private static final QName _Operation_QNAME = new QName("", "Operation");
    private static final QName _MappingRequired_QNAME = new QName("", "MappingRequired");
    private static final QName _CONDITIONID_QNAME = new QName("", "CONDITIONID");
    private static final QName _COMPGROUP_QNAME = new QName("", "COMPGROUP");
    private static final QName _COUNTER_QNAME = new QName("", "COUNTER");
    private static final QName _LEXTRACTOR_QNAME = new QName("", "LEXTRACTOR");
    private static final QName _REXTRACTOR_QNAME = new QName("", "REXTRACTOR");
    private static final QName _SplitCounter_QNAME = new QName("", "SplitCounter");
    private static final QName _Multiplicity_QNAME = new QName("", "Multiplicity");
    private static final QName _ReceiverConditionId_QNAME = new QName("", "ReceiverConditionId");
    private static final QName _ExtractorId_QNAME = new QName("", "ExtractorId");
    private static final QName _ExtractorData_QNAME = new QName("", "ExtractorData");
    private static final QName _UseGlobal_QNAME = new QName("", "UseGlobal");
    private static final QName _EXTRACTORID_QNAME = new QName("", "EXTRACTORID");
    private static final QName _VALUE_QNAME = new QName("", "VALUE");
    private static final QName _DATATYPE_QNAME = new QName("", "DATATYPE");
    private static final QName _MULTLINE_QNAME = new QName("", "MULTLINE");
    private static final QName _COBJNS_QNAME = new QName("", "COBJNS");
    private static final QName _COBJNAME_QNAME = new QName("", "COBJNAME");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.rsug.zatupka.allinone
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NSM }
     * 
     * @return
     *     the new instance of {@link NSM }
     */
    public NSM createNSM() {
        return new NSM();
    }

    /**
     * Create an instance of {@link AllInOne }
     * 
     * @return
     *     the new instance of {@link AllInOne }
     */
    public AllInOne createAllInOne() {
        return new AllInOne();
    }

    /**
     * Create an instance of {@link SenderConnectivity }
     * 
     * @return
     *     the new instance of {@link SenderConnectivity }
     */
    public SenderConnectivity createSenderConnectivity() {
        return new SenderConnectivity();
    }

    /**
     * Create an instance of {@link AllInOneAttributes }
     * 
     * @return
     *     the new instance of {@link AllInOneAttributes }
     */
    public AllInOneAttributes createAllInOneAttributes() {
        return new AllInOneAttributes();
    }

    /**
     * Create an instance of {@link AdapterTypeData }
     * 
     * @return
     *     the new instance of {@link AdapterTypeData }
     */
    public AdapterTypeData createAdapterTypeData() {
        return new AdapterTypeData();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     * @return
     *     the new instance of {@link Attribute }
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Namespace }
     * 
     * @return
     *     the new instance of {@link Namespace }
     */
    public Namespace createNamespace() {
        return new Namespace();
    }

    /**
     * Create an instance of {@link Value }
     * 
     * @return
     *     the new instance of {@link Value }
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Users }
     * 
     * @return
     *     the new instance of {@link Users }
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link NamespaceMapping }
     * 
     * @return
     *     the new instance of {@link NamespaceMapping }
     */
    public NamespaceMapping createNamespaceMapping() {
        return new NamespaceMapping();
    }

    /**
     * Create an instance of {@link NSM.Definition }
     * 
     * @return
     *     the new instance of {@link NSM.Definition }
     */
    public NSM.Definition createNSMDefinition() {
        return new NSM.Definition();
    }

    /**
     * Create an instance of {@link NoReceiverBehaviour }
     * 
     * @return
     *     the new instance of {@link NoReceiverBehaviour }
     */
    public NoReceiverBehaviour createNoReceiverBehaviour() {
        return new NoReceiverBehaviour();
    }

    /**
     * Create an instance of {@link ReceiverConfigurations }
     * 
     * @return
     *     the new instance of {@link ReceiverConfigurations }
     */
    public ReceiverConfigurations createReceiverConfigurations() {
        return new ReceiverConfigurations();
    }

    /**
     * Create an instance of {@link ReceiverConfiguration }
     * 
     * @return
     *     the new instance of {@link ReceiverConfiguration }
     */
    public ReceiverConfiguration createReceiverConfiguration() {
        return new ReceiverConfiguration();
    }

    /**
     * Create an instance of {@link Receiver }
     * 
     * @return
     *     the new instance of {@link Receiver }
     */
    public Receiver createReceiver() {
        return new Receiver();
    }

    /**
     * Create an instance of {@link TRDEXTRACTORT }
     * 
     * @return
     *     the new instance of {@link TRDEXTRACTORT }
     */
    public TRDEXTRACTORT createTRDEXTRACTORT() {
        return new TRDEXTRACTORT();
    }

    /**
     * Create an instance of {@link InterfaceDeterminations }
     * 
     * @return
     *     the new instance of {@link InterfaceDeterminations }
     */
    public InterfaceDeterminations createInterfaceDeterminations() {
        return new InterfaceDeterminations();
    }

    /**
     * Create an instance of {@link InterfaceDetermination }
     * 
     * @return
     *     the new instance of {@link InterfaceDetermination }
     */
    public InterfaceDetermination createInterfaceDetermination() {
        return new InterfaceDetermination();
    }

    /**
     * Create an instance of {@link Interfaces }
     * 
     * @return
     *     the new instance of {@link Interfaces }
     */
    public Interfaces createInterfaces() {
        return new Interfaces();
    }

    /**
     * Create an instance of {@link Interface }
     * 
     * @return
     *     the new instance of {@link Interface }
     */
    public Interface createInterface() {
        return new Interface();
    }

    /**
     * Create an instance of {@link Binding }
     * 
     * @return
     *     the new instance of {@link Binding }
     */
    public Binding createBinding() {
        return new Binding();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     * @return
     *     the new instance of {@link Properties }
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     * @return
     *     the new instance of {@link Property }
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     * @return
     *     the new instance of {@link Condition }
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link RDSCONDSHORT }
     * 
     * @return
     *     the new instance of {@link RDSCONDSHORT }
     */
    public RDSCONDSHORT createRDSCONDSHORT() {
        return new RDSCONDSHORT();
    }

    /**
     * Create an instance of {@link CONDLINE }
     * 
     * @return
     *     the new instance of {@link CONDLINE }
     */
    public CONDLINE createCONDLINE() {
        return new CONDLINE();
    }

    /**
     * Create an instance of {@link SplitItems }
     * 
     * @return
     *     the new instance of {@link SplitItems }
     */
    public SplitItems createSplitItems() {
        return new SplitItems();
    }

    /**
     * Create an instance of {@link SplitItem }
     * 
     * @return
     *     the new instance of {@link SplitItem }
     */
    public SplitItem createSplitItem() {
        return new SplitItem();
    }

    /**
     * Create an instance of {@link ReceiverAssignmentList }
     * 
     * @return
     *     the new instance of {@link ReceiverAssignmentList }
     */
    public ReceiverAssignmentList createReceiverAssignmentList() {
        return new ReceiverAssignmentList();
    }

    /**
     * Create an instance of {@link ReceiverAssignment }
     * 
     * @return
     *     the new instance of {@link ReceiverAssignment }
     */
    public ReceiverAssignment createReceiverAssignment() {
        return new ReceiverAssignment();
    }

    /**
     * Create an instance of {@link ReceiverIds }
     * 
     * @return
     *     the new instance of {@link ReceiverIds }
     */
    public ReceiverIds createReceiverIds() {
        return new ReceiverIds();
    }

    /**
     * Create an instance of {@link DynamicalRouting }
     * 
     * @return
     *     the new instance of {@link DynamicalRouting }
     */
    public DynamicalRouting createDynamicalRouting() {
        return new DynamicalRouting();
    }

    /**
     * Create an instance of {@link ReceiverConnectivityList }
     * 
     * @return
     *     the new instance of {@link ReceiverConnectivityList }
     */
    public ReceiverConnectivityList createReceiverConnectivityList() {
        return new ReceiverConnectivityList();
    }

    /**
     * Create an instance of {@link ReceiverConnectivity }
     * 
     * @return
     *     the new instance of {@link ReceiverConnectivity }
     */
    public ReceiverConnectivity createReceiverConnectivity() {
        return new ReceiverConnectivity();
    }

    /**
     * Create an instance of {@link HeaderMapping }
     * 
     * @return
     *     the new instance of {@link HeaderMapping }
     */
    public HeaderMapping createHeaderMapping() {
        return new HeaderMapping();
    }

    /**
     * Create an instance of {@link FieldMapping }
     * 
     * @return
     *     the new instance of {@link FieldMapping }
     */
    public FieldMapping createFieldMapping() {
        return new FieldMapping();
    }

    /**
     * Create an instance of {@link Field }
     * 
     * @return
     *     the new instance of {@link Field }
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Extractor }
     * 
     * @return
     *     the new instance of {@link Extractor }
     */
    public Extractor createExtractor() {
        return new Extractor();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     * @return
     *     the new instance of {@link Conditions }
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link ScenarioConfiguration }
     * 
     * @return
     *     the new instance of {@link ScenarioConfiguration }
     */
    public ScenarioConfiguration createScenarioConfiguration() {
        return new ScenarioConfiguration();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     * @return
     *     the new instance of {@link Parameters }
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     * @return
     *     the new instance of {@link Parameter }
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link io.rsug.zatupka.allinone.Definition }
     * 
     * @return
     *     the new instance of {@link io.rsug.zatupka.allinone.Definition }
     */
    public io.rsug.zatupka.allinone.Definition createDefinition() {
        return new io.rsug.zatupka.allinone.Definition();
    }

    /**
     * Create an instance of {@link TRDEXTRACTOR }
     * 
     * @return
     *     the new instance of {@link TRDEXTRACTOR }
     */
    public TRDEXTRACTOR createTRDEXTRACTOR() {
        return new TRDEXTRACTOR();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ValidationMode")
    public JAXBElement<BigInteger> createValidationMode(BigInteger value) {
        return new JAXBElement<>(_ValidationMode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "VirusScanMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVirusScanMode(String value) {
        return new JAXBElement<>(_VirusScanMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "IfNoReceiverFound")
    public JAXBElement<BigInteger> createIfNoReceiverFound(BigInteger value) {
        return new JAXBElement<>(_IfNoReceiverFound_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DefaultReceiverId")
    public JAXBElement<String> createDefaultReceiverId(String value) {
        return new JAXBElement<>(_DefaultReceiverId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ReceiverId")
    public JAXBElement<String> createReceiverId(String value) {
        return new JAXBElement<>(_ReceiverId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PartyExtractor")
    public JAXBElement<TRDEXTRACTORT> createPartyExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<>(_PartyExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PartyAgencyExtractor")
    public JAXBElement<TRDEXTRACTORT> createPartyAgencyExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<>(_PartyAgencyExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PartySchemaExtractor")
    public JAXBElement<TRDEXTRACTORT> createPartySchemaExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<>(_PartySchemaExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ServiceExtractor")
    public JAXBElement<TRDEXTRACTORT> createServiceExtractor(TRDEXTRACTORT value) {
        return new JAXBElement<>(_ServiceExtractor_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "QualityOfService")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createQualityOfService(String value) {
        return new JAXBElement<>(_QualityOfService_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ReceiverConnectivityId")
    public JAXBElement<String> createReceiverConnectivityId(String value) {
        return new JAXBElement<>(_ReceiverConnectivityId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "InterfaceConditionId")
    public JAXBElement<String> createInterfaceConditionId(String value) {
        return new JAXBElement<>(_InterfaceConditionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "InterfaceName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInterfaceName(String value) {
        return new JAXBElement<>(_InterfaceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "InterfaceNamespace")
    public JAXBElement<String> createInterfaceNamespace(String value) {
        return new JAXBElement<>(_InterfaceNamespace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Counter")
    public JAXBElement<BigInteger> createCounter(BigInteger value) {
        return new JAXBElement<>(_Counter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Operation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOperation(String value) {
        return new JAXBElement<>(_Operation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "MappingRequired")
    public JAXBElement<BigInteger> createMappingRequired(BigInteger value) {
        return new JAXBElement<>(_MappingRequired_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "CONDITIONID")
    public JAXBElement<String> createCONDITIONID(String value) {
        return new JAXBElement<>(_CONDITIONID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "COMPGROUP")
    public JAXBElement<BigInteger> createCOMPGROUP(BigInteger value) {
        return new JAXBElement<>(_COMPGROUP_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "COUNTER")
    public JAXBElement<BigInteger> createCOUNTER(BigInteger value) {
        return new JAXBElement<>(_COUNTER_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "LEXTRACTOR")
    public JAXBElement<TRDEXTRACTORT> createLEXTRACTOR(TRDEXTRACTORT value) {
        return new JAXBElement<>(_LEXTRACTOR_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "REXTRACTOR")
    public JAXBElement<TRDEXTRACTORT> createREXTRACTOR(TRDEXTRACTORT value) {
        return new JAXBElement<>(_REXTRACTOR_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SplitCounter")
    public JAXBElement<BigInteger> createSplitCounter(BigInteger value) {
        return new JAXBElement<>(_SplitCounter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Multiplicity")
    public JAXBElement<String> createMultiplicity(String value) {
        return new JAXBElement<>(_Multiplicity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ReceiverConditionId")
    public JAXBElement<String> createReceiverConditionId(String value) {
        return new JAXBElement<>(_ReceiverConditionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ExtractorId")
    public JAXBElement<String> createExtractorId(String value) {
        return new JAXBElement<>(_ExtractorId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRDEXTRACTORT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ExtractorData")
    public JAXBElement<TRDEXTRACTORT> createExtractorData(TRDEXTRACTORT value) {
        return new JAXBElement<>(_ExtractorData_QNAME, TRDEXTRACTORT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "UseGlobal")
    public JAXBElement<Boolean> createUseGlobal(Boolean value) {
        return new JAXBElement<>(_UseGlobal_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "EXTRACTORID")
    public JAXBElement<String> createEXTRACTORID(String value) {
        return new JAXBElement<>(_EXTRACTORID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "VALUE")
    public JAXBElement<String> createVALUE(String value) {
        return new JAXBElement<>(_VALUE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DATATYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDATATYPE(String value) {
        return new JAXBElement<>(_DATATYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "MULTLINE")
    public JAXBElement<String> createMULTLINE(String value) {
        return new JAXBElement<>(_MULTLINE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "COBJNS")
    public JAXBElement<String> createCOBJNS(String value) {
        return new JAXBElement<>(_COBJNS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "COBJNAME")
    public JAXBElement<String> createCOBJNAME(String value) {
        return new JAXBElement<>(_COBJNAME_QNAME, String.class, null, value);
    }

}
