//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:24:20 PM MSK
//

package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <sequence minOccurs="0">
 *           <element ref="{}ReceiverConnectivityId"/>
 *           <element ref="{}ValidationMode"/>
 *         </sequence>
 *         <element ref="{}VirusScanMode" minOccurs="0"/>
 *         <element ref="{}AllInOneAttributes" minOccurs="0"/>
 *         <element ref="{}HeaderMapping" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiverConnectivityId",
    "validationMode",
    "virusScanMode",
    "allInOneAttributes",
    "headerMapping"
})
@XmlRootElement(name = "ReceiverConnectivity")
public class ReceiverConnectivity {

    @XmlElement(name = "ReceiverConnectivityId")
    protected String receiverConnectivityId;
    @XmlElement(name = "ValidationMode")
    protected BigInteger validationMode;
    @XmlElement(name = "VirusScanMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String virusScanMode;
    @XmlElement(name = "AllInOneAttributes")
    protected AllInOneAttributes allInOneAttributes;
    @XmlElement(name = "HeaderMapping")
    protected HeaderMapping headerMapping;

    /**
     * Gets the value of the receiverConnectivityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverConnectivityId() {
        return receiverConnectivityId;
    }

    /**
     * Sets the value of the receiverConnectivityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverConnectivityId(String value) {
        this.receiverConnectivityId = value;
    }

    /**
     * Gets the value of the validationMode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValidationMode() {
        return validationMode;
    }

    /**
     * Sets the value of the validationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValidationMode(BigInteger value) {
        this.validationMode = value;
    }

    /**
     * Gets the value of the virusScanMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirusScanMode() {
        return virusScanMode;
    }

    /**
     * Sets the value of the virusScanMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirusScanMode(String value) {
        this.virusScanMode = value;
    }

    /**
     * Gets the value of the allInOneAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AllInOneAttributes }
     *     
     */
    public AllInOneAttributes getAllInOneAttributes() {
        return allInOneAttributes;
    }

    /**
     * Sets the value of the allInOneAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllInOneAttributes }
     *     
     */
    public void setAllInOneAttributes(AllInOneAttributes value) {
        this.allInOneAttributes = value;
    }

    /**
     * Gets the value of the headerMapping property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderMapping }
     *     
     */
    public HeaderMapping getHeaderMapping() {
        return headerMapping;
    }

    /**
     * Sets the value of the headerMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderMapping }
     *     
     */
    public void setHeaderMapping(HeaderMapping value) {
        this.headerMapping = value;
    }

}
