//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:30 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}PartyExtractor"/>
 *         <element ref="{}PartyAgencyExtractor"/>
 *         <element ref="{}PartySchemaExtractor"/>
 *         <element ref="{}ServiceExtractor"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partyExtractor",
    "partyAgencyExtractor",
    "partySchemaExtractor",
    "serviceExtractor"
})
@XmlRootElement(name = "Receiver")
public class Receiver {

    @XmlElement(name = "PartyExtractor", required = true)
    protected TRDEXTRACTORT partyExtractor;
    @XmlElement(name = "PartyAgencyExtractor", required = true)
    protected TRDEXTRACTORT partyAgencyExtractor;
    @XmlElement(name = "PartySchemaExtractor", required = true)
    protected TRDEXTRACTORT partySchemaExtractor;
    @XmlElement(name = "ServiceExtractor", required = true)
    protected TRDEXTRACTORT serviceExtractor;

    /**
     * Gets the value of the partyExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getPartyExtractor() {
        return partyExtractor;
    }

    /**
     * Sets the value of the partyExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setPartyExtractor(TRDEXTRACTORT value) {
        this.partyExtractor = value;
    }

    /**
     * Gets the value of the partyAgencyExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getPartyAgencyExtractor() {
        return partyAgencyExtractor;
    }

    /**
     * Sets the value of the partyAgencyExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setPartyAgencyExtractor(TRDEXTRACTORT value) {
        this.partyAgencyExtractor = value;
    }

    /**
     * Gets the value of the partySchemaExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getPartySchemaExtractor() {
        return partySchemaExtractor;
    }

    /**
     * Sets the value of the partySchemaExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setPartySchemaExtractor(TRDEXTRACTORT value) {
        this.partySchemaExtractor = value;
    }

    /**
     * Gets the value of the serviceExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getServiceExtractor() {
        return serviceExtractor;
    }

    /**
     * Sets the value of the serviceExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setServiceExtractor(TRDEXTRACTORT value) {
        this.serviceExtractor = value;
    }

}
