//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.11 at 05:39:49 PM MSK 
//


package io.rsug.zatupka.allinone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PartyExtractor"/>
 *         &lt;element ref="{}PartyAgencyExtractor"/>
 *         &lt;element ref="{}PartySchemaExtractor"/>
 *         &lt;element ref="{}ServiceExtractor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partyExtractor",
    "partyAgencyExtractor",
    "partySchemaExtractor",
    "serviceExtractor"
})
@XmlRootElement(name = "Receiver")
public class Receiver {

    @XmlElement(name = "PartyExtractor", required = true)
    protected TRDEXTRACTORT partyExtractor;
    @XmlElement(name = "PartyAgencyExtractor", required = true)
    protected TRDEXTRACTORT partyAgencyExtractor;
    @XmlElement(name = "PartySchemaExtractor", required = true)
    protected TRDEXTRACTORT partySchemaExtractor;
    @XmlElement(name = "ServiceExtractor", required = true)
    protected TRDEXTRACTORT serviceExtractor;

    /**
     * Gets the value of the partyExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getPartyExtractor() {
        return partyExtractor;
    }

    /**
     * Sets the value of the partyExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setPartyExtractor(TRDEXTRACTORT value) {
        this.partyExtractor = value;
    }

    /**
     * Gets the value of the partyAgencyExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getPartyAgencyExtractor() {
        return partyAgencyExtractor;
    }

    /**
     * Sets the value of the partyAgencyExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setPartyAgencyExtractor(TRDEXTRACTORT value) {
        this.partyAgencyExtractor = value;
    }

    /**
     * Gets the value of the partySchemaExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getPartySchemaExtractor() {
        return partySchemaExtractor;
    }

    /**
     * Sets the value of the partySchemaExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setPartySchemaExtractor(TRDEXTRACTORT value) {
        this.partySchemaExtractor = value;
    }

    /**
     * Gets the value of the serviceExtractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public TRDEXTRACTORT getServiceExtractor() {
        return serviceExtractor;
    }

    /**
     * Sets the value of the serviceExtractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORT }
     *     
     */
    public void setServiceExtractor(TRDEXTRACTORT value) {
        this.serviceExtractor = value;
    }

}
