//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.17 at 07:35:23 PM MSK 
//


package io.rsug.zatupka.allinone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ReceiverId" minOccurs="0"/>
 *         &lt;element ref="{}Receiver"/>
 *         &lt;element ref="{}QualityOfService" minOccurs="0"/>
 *         &lt;element ref="{}InterfaceDeterminations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiverId",
    "receiver",
    "qualityOfService",
    "interfaceDeterminations"
})
@XmlRootElement(name = "ReceiverConfiguration")
public class ReceiverConfiguration {

    @XmlElement(name = "ReceiverId")
    protected String receiverId;
    @XmlElement(name = "Receiver", required = true)
    protected Receiver receiver;
    @XmlElement(name = "QualityOfService")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String qualityOfService;
    @XmlElement(name = "InterfaceDeterminations", required = true)
    protected InterfaceDeterminations interfaceDeterminations;

    /**
     * Gets the value of the receiverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * Sets the value of the receiverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverId(String value) {
        this.receiverId = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link Receiver }
     *     
     */
    public Receiver getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receiver }
     *     
     */
    public void setReceiver(Receiver value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the qualityOfService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualityOfService() {
        return qualityOfService;
    }

    /**
     * Sets the value of the qualityOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualityOfService(String value) {
        this.qualityOfService = value;
    }

    /**
     * Gets the value of the interfaceDeterminations property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceDeterminations }
     *     
     */
    public InterfaceDeterminations getInterfaceDeterminations() {
        return interfaceDeterminations;
    }

    /**
     * Sets the value of the interfaceDeterminations property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceDeterminations }
     *     
     */
    public void setInterfaceDeterminations(InterfaceDeterminations value) {
        this.interfaceDeterminations = value;
    }

}
