//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}ReceiverConditionId" minOccurs="0"/>
 *         <element ref="{}ReceiverIds"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiverConditionId",
    "receiverIds"
})
@XmlRootElement(name = "ReceiverAssignment")
public class ReceiverAssignment {

    @XmlElement(name = "ReceiverConditionId")
    protected String receiverConditionId;
    @XmlElement(name = "ReceiverIds", required = true)
    protected ReceiverIds receiverIds;

    /**
     * Gets the value of the receiverConditionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverConditionId() {
        return receiverConditionId;
    }

    /**
     * Sets the value of the receiverConditionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverConditionId(String value) {
        this.receiverConditionId = value;
    }

    /**
     * Gets the value of the receiverIds property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverIds }
     *     
     */
    public ReceiverIds getReceiverIds() {
        return receiverIds;
    }

    /**
     * Sets the value of the receiverIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverIds }
     *     
     */
    public void setReceiverIds(ReceiverIds value) {
        this.receiverIds = value;
    }

}
