//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.08 at 08:01:28 AM MSK 
//


package io.rsug.zatupka.allinone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ReceiverConditionId" minOccurs="0"/>
 *         &lt;element ref="{}ReceiverIds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiverConditionId",
    "receiverIds"
})
@XmlRootElement(name = "ReceiverAssignment")
public class ReceiverAssignment {

    @XmlElement(name = "ReceiverConditionId")
    protected String receiverConditionId;
    @XmlElement(name = "ReceiverIds", required = true)
    protected ReceiverId receiverIds;

    /**
     * Gets the value of the receiverConditionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverConditionId() {
        return receiverConditionId;
    }

    /**
     * Sets the value of the receiverConditionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverConditionId(String value) {
        this.receiverConditionId = value;
    }

    /**
     * Gets the value of the receiverIds property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverId }
     *     
     */
    public ReceiverId getReceiverIds() {
        return receiverIds;
    }

    /**
     * Sets the value of the receiverIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverId }
     *     
     */
    public void setReceiverIds(ReceiverId value) {
        this.receiverIds = value;
    }

}
