//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:30 PM MSK
//

package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}ValidationMode"/>
 *         <element ref="{}VirusScanMode" minOccurs="0"/>
 *         <element ref="{}AllInOneAttributes"/>
 *         <element ref="{}Users" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validationMode",
    "virusScanMode",
    "allInOneAttributes",
    "users"
})
@XmlRootElement(name = "SenderConnectivity")
public class SenderConnectivity {

    @XmlElement(name = "ValidationMode", required = true)
    protected BigInteger validationMode;
    @XmlElement(name = "VirusScanMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String virusScanMode;
    @XmlElement(name = "AllInOneAttributes", required = true)
    protected AllInOneAttributes allInOneAttributes;
    @XmlElement(name = "Users")
    protected Users users;

    /**
     * Gets the value of the validationMode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValidationMode() {
        return validationMode;
    }

    /**
     * Sets the value of the validationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValidationMode(BigInteger value) {
        this.validationMode = value;
    }

    /**
     * Gets the value of the virusScanMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirusScanMode() {
        return virusScanMode;
    }

    /**
     * Sets the value of the virusScanMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirusScanMode(String value) {
        this.virusScanMode = value;
    }

    /**
     * Gets the value of the allInOneAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AllInOneAttributes }
     *     
     */
    public AllInOneAttributes getAllInOneAttributes() {
        return allInOneAttributes;
    }

    /**
     * Sets the value of the allInOneAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllInOneAttributes }
     *     
     */
    public void setAllInOneAttributes(AllInOneAttributes value) {
        this.allInOneAttributes = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link Users }
     *     
     */
    public Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link Users }
     *     
     */
    public void setUsers(Users value) {
        this.users = value;
    }

}
