//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.09 at 05:47:54 AM MSK 
//


package io.rsug.zatupka.allinone;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ValidationMode"/>
 *         &lt;element ref="{}VirusScanMode"/>
 *         &lt;element ref="{}AllInOneAttributes"/>
 *         &lt;element ref="{}Users"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validationMode",
    "virusScanMode",
    "allInOneAttributes",
    "users"
})
@XmlRootElement(name = "SenderConnectivity")
public class SenderConnectivity {

    @XmlElement(name = "ValidationMode", required = true)
    protected BigInteger validationMode;
    @XmlElement(name = "VirusScanMode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String virusScanMode;
    @XmlElement(name = "AllInOneAttributes", required = true)
    protected AllInOneAttributes allInOneAttributes;
    @XmlElement(name = "Users", required = true)
    protected Users users;

    /**
     * Gets the value of the validationMode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValidationMode() {
        return validationMode;
    }

    /**
     * Sets the value of the validationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValidationMode(BigInteger value) {
        this.validationMode = value;
    }

    /**
     * Gets the value of the virusScanMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirusScanMode() {
        return virusScanMode;
    }

    /**
     * Sets the value of the virusScanMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirusScanMode(String value) {
        this.virusScanMode = value;
    }

    /**
     * Gets the value of the allInOneAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AllInOneAttributes }
     *     
     */
    public AllInOneAttributes getAllInOneAttributes() {
        return allInOneAttributes;
    }

    /**
     * Sets the value of the allInOneAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllInOneAttributes }
     *     
     */
    public void setAllInOneAttributes(AllInOneAttributes value) {
        this.allInOneAttributes = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link Users }
     *     
     */
    public Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link Users }
     *     
     */
    public void setUsers(Users value) {
        this.users = value;
    }

}
