//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:55:23 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRD_EXTRACTOR complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TRD_EXTRACTOR">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}TRD_EXTRACTOR"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRD_EXTRACTOR", propOrder = {
    "trdextractor"
})
public class TRDEXTRACTORT {

    @XmlElement(name = "TRD_EXTRACTOR", required = true)
    protected TRDEXTRACTOR trdextractor;

    /**
     * Gets the value of the trdextractor property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTOR }
     *     
     */
    public TRDEXTRACTOR getTRDEXTRACTOR() {
        return trdextractor;
    }

    /**
     * Sets the value of the trdextractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTOR }
     *     
     */
    public void setTRDEXTRACTOR(TRDEXTRACTOR value) {
        this.trdextractor = value;
    }

}
