//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:30 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}EXTRACTORID"/>
 *         <element name="TYPE" type="{}TRD_EXTRACTOR_TYPEENUM"/>
 *         <element ref="{}VALUE"/>
 *         <element ref="{}DATATYPE"/>
 *         <element ref="{}MULTLINE"/>
 *         <element ref="{}COBJNS"/>
 *         <element ref="{}COBJNAME"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extractorid",
    "type",
    "value",
    "datatype",
    "multline",
    "cobjns",
    "cobjname"
})
@XmlRootElement(name = "TRD_EXTRACTOR")
public class TRDEXTRACTOR {

    @XmlElement(name = "EXTRACTORID", required = true)
    protected String extractorid;
    @XmlElement(name = "TYPE", required = true)
    @XmlSchemaType(name = "string")
    protected TRDEXTRACTORTYPEENUM type;
    @XmlElement(name = "VALUE", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String value;
    @XmlElement(name = "DATATYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String datatype;
    @XmlElement(name = "MULTLINE", required = true)
    protected String multline;
    @XmlElement(name = "COBJNS", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String cobjns;
    @XmlElement(name = "COBJNAME", required = true)
    protected String cobjname;

    /**
     * Gets the value of the extractorid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXTRACTORID() {
        return extractorid;
    }

    /**
     * Sets the value of the extractorid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXTRACTORID(String value) {
        this.extractorid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TRDEXTRACTORTYPEENUM }
     *     
     */
    public TRDEXTRACTORTYPEENUM getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRDEXTRACTORTYPEENUM }
     *     
     */
    public void setTYPE(TRDEXTRACTORTYPEENUM value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALUE() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALUE(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATATYPE() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATATYPE(String value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the multline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMULTLINE() {
        return multline;
    }

    /**
     * Sets the value of the multline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMULTLINE(String value) {
        this.multline = value;
    }

    /**
     * Gets the value of the cobjns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOBJNS() {
        return cobjns;
    }

    /**
     * Sets the value of the cobjns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOBJNS(String value) {
        this.cobjns = value;
    }

    /**
     * Gets the value of the cobjname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOBJNAME() {
        return cobjname;
    }

    /**
     * Sets the value of the cobjname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOBJNAME(String value) {
        this.cobjname = value;
    }

}
