//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.19 at 06:20:59 PM MSK 
//


package io.rsug.zatupka.allinone;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRD_EXTRACTOR_TYPEENUM.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRD_EXTRACTOR_TYPEENUM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KO"/>
 *     &lt;enumeration value="XP"/>
 *     &lt;enumeration value="CT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TRD_EXTRACTOR_TYPEENUM")
@XmlEnum
public enum TRDEXTRACTORTYPEENUM {

    KO,
    XP,
    CT;

    public String value() {
        return name();
    }

    public static TRDEXTRACTORTYPEENUM fromValue(String v) {
        return valueOf(v);
    }

}
