//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:24:20 PM MSK
//

package io.rsug.zatupka.allinone;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for TRD_EXTRACTOR_TYPEENUM</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="TRD_EXTRACTOR_TYPEENUM">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="KO"/>
 *     <enumeration value="XP"/>
 *     <enumeration value="CT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "TRD_EXTRACTOR_TYPEENUM")
@XmlEnum
public enum TRDEXTRACTORTYPEENUM {

    KO,
    XP,
    CT;

    public String value() {
        return name();
    }

    public static TRDEXTRACTORTYPEENUM fromValue(String v) {
        return valueOf(v);
    }

}
