//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:30 PM MSK
//

package io.rsug.zatupka.allinone;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Representation" maxOccurs="unbounded" form="unqualified">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="system" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *                   <element name="objectTypeName" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *                   <element name="value" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="groupName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="groupid" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "representation"
})
@XmlRootElement(name = "Valuemapping")
public class Valuemapping {

    @XmlElement(name = "Representation", required = true)
    protected List<Valuemapping.Representation> representation;
    @XmlAttribute(name = "groupName", required = true)
    protected String groupName;
    @XmlAttribute(name = "groupid", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String groupid;

    /**
     * Gets the value of the representation property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore, any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the representation property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRepresentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Valuemapping.Representation }
     * </p>
     * 
     * 
     * @return
     *     The value of the representation property.
     */
    public List<Valuemapping.Representation> getRepresentation() {
        if (representation == null) {
            representation = new ArrayList<>();
        }
        return this.representation;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the groupid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * Sets the value of the groupid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupid(String value) {
        this.groupid = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="system" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
     *         <element name="objectTypeName" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
     *         <element name="value" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "system",
        "objectTypeName",
        "value"
    })
    public static class Representation {

        @XmlElement(required = true)
        protected String system;
        @XmlElement(required = true)
        protected String objectTypeName;
        @XmlElement(required = true)
        protected String value;

        /**
         * Gets the value of the system property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystem(String value) {
            this.system = value;
        }

        /**
         * Gets the value of the objectTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectTypeName() {
            return objectTypeName;
        }

        /**
         * Sets the value of the objectTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectTypeName(String value) {
            this.objectTypeName = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
