//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.08 at 08:43:39 AM MSK 
//


package io.rsug.zatupka.channel;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.rsug.zatupka.channel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParamValue_QNAME = new QName("urn:sap-com:xi:xiChannel", "ParamValue");
    private final static QName _TransportProtocol_QNAME = new QName("urn:sap-com:xi:xiChannel", "TransportProtocol");
    private final static QName _EngineType_QNAME = new QName("urn:sap-com:xi:xiChannel", "EngineType");
    private final static QName _ChannelDirection_QNAME = new QName("urn:sap-com:xi:xiChannel", "ChannelDirection");
    private final static QName _MessageProtocol_QNAME = new QName("urn:sap-com:xi:xiChannel", "MessageProtocol");
    private final static QName _MessageProtocolVersion_QNAME = new QName("urn:sap-com:xi:xiChannel", "MessageProtocolVersion");
    private final static QName _ParamName_QNAME = new QName("urn:sap-com:xi:xiChannel", "ParamName");
    private final static QName _TransportProtocolVersion_QNAME = new QName("urn:sap-com:xi:xiChannel", "TransportProtocolVersion");
    private final static QName _ModuleType_QNAME = new QName("urn:sap-com:xi:xiChannel", "ModuleType");
    private final static QName _Position_QNAME = new QName("urn:sap-com:xi:xiChannel", "Position");
    private final static QName _ModuleNs_QNAME = new QName("urn:sap-com:xi:xiChannel", "ModuleNs");
    private final static QName _ModuleName_QNAME = new QName("urn:sap-com:xi:xiChannel", "ModuleName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.rsug.zatupka.channel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChannelAttributes }
     * 
     */
    public ChannelAttributes createChannelAttributes() {
        return new ChannelAttributes();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData }
     * 
     */
    public ChannelAttributes.AdapterTypeData createChannelAttributesAdapterTypeData() {
        return new ChannelAttributes.AdapterTypeData();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData.Attribute }
     * 
     */
    public ChannelAttributes.AdapterTypeData.Attribute createChannelAttributesAdapterTypeDataAttribute() {
        return new ChannelAttributes.AdapterTypeData.Attribute();
    }

    /**
     * Create an instance of {@link PipelineConfig }
     * 
     */
    public PipelineConfig createPipelineConfig() {
        return new PipelineConfig();
    }

    /**
     * Create an instance of {@link FromPartySchema }
     * 
     */
    public FromPartySchema createFromPartySchema() {
        return new FromPartySchema();
    }

    /**
     * Create an instance of {@link ToPartySchema }
     * 
     */
    public ToPartySchema createToPartySchema() {
        return new ToPartySchema();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link EngineName }
     * 
     */
    public EngineName createEngineName() {
        return new EngineName();
    }

    /**
     * Create an instance of {@link FromPartyAgency }
     * 
     */
    public FromPartyAgency createFromPartyAgency() {
        return new FromPartyAgency();
    }

    /**
     * Create an instance of {@link ToPartyAgency }
     * 
     */
    public ToPartyAgency createToPartyAgency() {
        return new ToPartyAgency();
    }

    /**
     * Create an instance of {@link PipelineAttributes }
     * 
     */
    public PipelineAttributes createPipelineAttributes() {
        return new PipelineAttributes();
    }

    /**
     * Create an instance of {@link PipelineData }
     * 
     */
    public PipelineData createPipelineData() {
        return new PipelineData();
    }

    /**
     * Create an instance of {@link ModuleData }
     * 
     */
    public ModuleData createModuleData() {
        return new ModuleData();
    }

    /**
     * Create an instance of {@link ModuleConfig }
     * 
     */
    public ModuleConfig createModuleConfig() {
        return new ModuleConfig();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData.Attribute.Namespace }
     * 
     */
    public ChannelAttributes.AdapterTypeData.Attribute.Namespace createChannelAttributesAdapterTypeDataAttributeNamespace() {
        return new ChannelAttributes.AdapterTypeData.Attribute.Namespace();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData.Attribute.Value }
     * 
     */
    public ChannelAttributes.AdapterTypeData.Attribute.Value createChannelAttributesAdapterTypeDataAttributeValue() {
        return new ChannelAttributes.AdapterTypeData.Attribute.Value();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ParamValue")
    public JAXBElement<String> createParamValue(String value) {
        return new JAXBElement<String>(_ParamValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "TransportProtocol")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransportProtocol(String value) {
        return new JAXBElement<String>(_TransportProtocol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "EngineType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEngineType(String value) {
        return new JAXBElement<String>(_EngineType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ChannelDirection")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createChannelDirection(String value) {
        return new JAXBElement<String>(_ChannelDirection_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "MessageProtocol")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMessageProtocol(String value) {
        return new JAXBElement<String>(_MessageProtocol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "MessageProtocolVersion")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMessageProtocolVersion(String value) {
        return new JAXBElement<String>(_MessageProtocolVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ParamName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParamName(String value) {
        return new JAXBElement<String>(_ParamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "TransportProtocolVersion")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransportProtocolVersion(String value) {
        return new JAXBElement<String>(_TransportProtocolVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ModuleType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createModuleType(String value) {
        return new JAXBElement<String>(_ModuleType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "Position")
    public JAXBElement<BigInteger> createPosition(BigInteger value) {
        return new JAXBElement<BigInteger>(_Position_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ModuleNs")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createModuleNs(String value) {
        return new JAXBElement<String>(_ModuleNs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ModuleName")
    public JAXBElement<String> createModuleName(String value) {
        return new JAXBElement<String>(_ModuleName_QNAME, String.class, null, value);
    }

}
