//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:17:37 PM MSK
//

package io.rsug.zatupka.xiobj;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi}modifBy"/>
 *         <element ref="{urn:sap-com:xi}modifAt"/>
 *         <element name="modifAtLong" type="{http://www.w3.org/2001/XMLSchema}integer" form="unqualified"/>
 *         <element ref="{urn:sap-com:xi}owner"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modifBy",
    "modifAt",
    "modifAtLong",
    "owner"
})
@XmlRootElement(name = "admInf")
public class AdmInf {

    @XmlElement(required = true)
    protected String modifBy;
    @XmlElement(required = true)
    protected String modifAt;
    @XmlElement(namespace = "", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Long modifAtLong;
    @XmlElement(required = true)
    protected String owner;

    /**
     * Gets the value of the modifBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifBy() {
        return modifBy;
    }

    /**
     * Sets the value of the modifBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifBy(String value) {
        this.modifBy = value;
    }

    /**
     * Gets the value of the modifAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifAt() {
        return modifAt;
    }

    /**
     * Sets the value of the modifAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifAt(String value) {
        this.modifAt = value;
    }

    /**
     * Gets the value of the modifAtLong property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getModifAtLong() {
        return modifAtLong;
    }

    /**
     * Sets the value of the modifAtLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setModifAtLong(Long value) {
        this.modifAtLong = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

}
