//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.07 at 09:30:16 PM MSK 
//


package io.rsug.zatupka.xiobj;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:sap-com:xi}modifBy"/>
 *         &lt;element ref="{urn:sap-com:xi}modifAt"/>
 *         &lt;element name="modifAtLong" type="{http://www.w3.org/2001/XMLSchema}integer" form="unqualified"/>
 *         &lt;element ref="{urn:sap-com:xi}owner"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modifBy",
    "modifAt",
    "modifAtLong",
    "owner"
})
@XmlRootElement(name = "admInf")
public class AdmInf {

    @XmlElement(required = true)
    protected String modifBy;
    @XmlElement(required = true)
    protected String modifAt;
    @XmlElement(namespace = "", required = true)
    protected BigInteger modifAtLong;
    @XmlElement(required = true)
    protected String owner;

    /**
     * Gets the value of the modifBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifBy() {
        return modifBy;
    }

    /**
     * Sets the value of the modifBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifBy(String value) {
        this.modifBy = value;
    }

    /**
     * Gets the value of the modifAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifAt() {
        return modifAt;
    }

    /**
     * Sets the value of the modifAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifAt(String value) {
        this.modifAt = value;
    }

    /**
     * Gets the value of the modifAtLong property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getModifAtLong() {
        return modifAtLong;
    }

    /**
     * Sets the value of the modifAtLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setModifAtLong(BigInteger value) {
        this.modifAtLong = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

}
