//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:54 PM MSK
//

package io.rsug.zatupka.xiobj;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="consider" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "clCxt")
public class ClCxt {

    @XmlAttribute(name = "consider", required = true)
    protected String consider;

    /**
     * Gets the value of the consider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsider() {
        return consider;
    }

    /**
     * Sets the value of the consider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsider(String value) {
        this.consider = value;
    }

}
