//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:17:37 PM MSK
//

package io.rsug.zatupka.xiobj;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi}admInf" minOccurs="0"/>
 *         <element ref="{urn:sap-com:xi}lnks" minOccurs="0"/>
 *         <element ref="{urn:sap-com:xi}textInfo"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "admInf",
    "lnks",
    "textInfo"
})
@XmlRootElement(name = "generic")
public class Generic {

    protected AdmInf admInf;
    protected Lnks lnks;
    @XmlElement(required = true)
    protected TextInfo textInfo;

    /**
     * Gets the value of the admInf property.
     * 
     * @return
     *     possible object is
     *     {@link AdmInf }
     *     
     */
    public AdmInf getAdmInf() {
        return admInf;
    }

    /**
     * Sets the value of the admInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdmInf }
     *     
     */
    public void setAdmInf(AdmInf value) {
        this.admInf = value;
    }

    /**
     * Gets the value of the lnks property.
     * 
     * @return
     *     possible object is
     *     {@link Lnks }
     *     
     */
    public Lnks getLnks() {
        return lnks;
    }

    /**
     * Sets the value of the lnks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lnks }
     *     
     */
    public void setLnks(Lnks value) {
        this.lnks = value;
    }

    /**
     * Gets the value of the textInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TextInfo }
     *     
     */
    public TextInfo getTextInfo() {
        return textInfo;
    }

    /**
     * Sets the value of the textInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextInfo }
     *     
     */
    public void setTextInfo(TextInfo value) {
        this.textInfo = value;
    }

}
