//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.21 at 08:48:49 PM MSK 
//


package io.rsug.zatupka.xiobj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:sap-com:xi}xiObj" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xiObj"
})
@XmlRootElement(name = "inner")
public class Inner {

    protected XiObj xiObj;

    /**
     * Gets the value of the xiObj property.
     * 
     * @return
     *     possible object is
     *     {@link XiObj }
     *     
     */
    public XiObj getXiObj() {
        return xiObj;
    }

    /**
     * Sets the value of the xiObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link XiObj }
     *     
     */
    public void setXiObj(XiObj value) {
        this.xiObj = value;
    }

}
