//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:51:45 PM MSK
//

package io.rsug.zatupka.xiobj;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi}xiObj" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xiObj"
})
@XmlRootElement(name = "inner")
public class Inner {

    protected XiObj xiObj;

    /**
     * Gets the value of the xiObj property.
     * 
     * @return
     *     possible object is
     *     {@link XiObj }
     *     
     */
    public XiObj getXiObj() {
        return xiObj;
    }

    /**
     * Sets the value of the xiObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link XiObj }
     *     
     */
    public void setXiObj(XiObj value) {
        this.xiObj = value;
    }

}
