//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:17:37 PM MSK
//

package io.rsug.zatupka.xiobj;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi}vc" minOccurs="0"/>
 *         <element ref="{urn:sap-com:xi}key"/>
 *       </sequence>
 *       <attribute name="rMode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vc",
    "key"
})
@XmlRootElement(name = "lnk")
public class Lnk {

    protected Vc vc;
    @XmlElement(required = true)
    protected Key key;
    @XmlAttribute(name = "rMode", required = true)
    protected String rMode;

    /**
     * Gets the value of the vc property.
     * 
     * @return
     *     possible object is
     *     {@link Vc }
     *     
     */
    public Vc getVc() {
        return vc;
    }

    /**
     * Sets the value of the vc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vc }
     *     
     */
    public void setVc(Vc value) {
        this.vc = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link Key }
     *     
     */
    public Key getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link Key }
     *     
     */
    public void setKey(Key value) {
        this.key = value;
    }

    /**
     * Gets the value of the rMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRMode() {
        return rMode;
    }

    /**
     * Sets the value of the rMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRMode(String value) {
        this.rMode = value;
    }

}
