//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:17:37 PM MSK
//

package io.rsug.zatupka.xiobj;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi}lnk"/>
 *       </sequence>
 *       <attribute name="kpos" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lnk"
})
@XmlRootElement(name = "lnkRole")
public class LnkRole {

    @XmlElement(required = true)
    protected Lnk lnk;
    @XmlAttribute(name = "kpos", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "integer")
    protected Long kpos;
    @XmlAttribute(name = "role", required = true)
    protected String role;

    /**
     * Gets the value of the lnk property.
     * 
     * @return
     *     possible object is
     *     {@link Lnk }
     *     
     */
    public Lnk getLnk() {
        return lnk;
    }

    /**
     * Sets the value of the lnk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lnk }
     *     
     */
    public void setLnk(Lnk value) {
        this.lnk = value;
    }

    /**
     * Gets the value of the kpos property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKpos() {
        return kpos;
    }

    /**
     * Sets the value of the kpos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKpos(Long value) {
        this.kpos = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
