//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.07 at 09:30:16 PM MSK 
//


package io.rsug.zatupka.xiobj;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.rsug.zatupka.xiobj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModifBy_QNAME = new QName("urn:sap-com:xi", "modifBy");
    private final static QName _ModifAt_QNAME = new QName("urn:sap-com:xi", "modifAt");
    private final static QName _Owner_QNAME = new QName("urn:sap-com:xi", "owner");
    private final static QName _Elem_QNAME = new QName("urn:sap-com:xi", "elem");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.rsug.zatupka.xiobj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Lnk }
     * 
     */
    public Lnk createLnk() {
        return new Lnk();
    }

    /**
     * Create an instance of {@link Vc }
     * 
     */
    public Vc createVc() {
        return new Vc();
    }

    /**
     * Create an instance of {@link ClCxt }
     * 
     */
    public ClCxt createClCxt() {
        return new ClCxt();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link XiObj }
     * 
     */
    public XiObj createXiObj() {
        return new XiObj();
    }

    /**
     * Create an instance of {@link IdInfo }
     * 
     */
    public IdInfo createIdInfo() {
        return new IdInfo();
    }

    /**
     * Create an instance of {@link Generic }
     * 
     */
    public Generic createGeneric() {
        return new Generic();
    }

    /**
     * Create an instance of {@link AdmInf }
     * 
     */
    public AdmInf createAdmInf() {
        return new AdmInf();
    }

    /**
     * Create an instance of {@link Lnks }
     * 
     */
    public Lnks createLnks() {
        return new Lnks();
    }

    /**
     * Create an instance of {@link LnkRole }
     * 
     */
    public LnkRole createLnkRole() {
        return new LnkRole();
    }

    /**
     * Create an instance of {@link TextInfo }
     * 
     */
    public TextInfo createTextInfo() {
        return new TextInfo();
    }

    /**
     * Create an instance of {@link TextObj }
     * 
     */
    public TextObj createTextObj() {
        return new TextObj();
    }

    /**
     * Create an instance of {@link Texts }
     * 
     */
    public Texts createTexts() {
        return new Texts();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "modifBy")
    public JAXBElement<String> createModifBy(String value) {
        return new JAXBElement<String>(_ModifBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "modifAt")
    public JAXBElement<String> createModifAt(String value) {
        return new JAXBElement<String>(_ModifAt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "owner")
    public JAXBElement<String> createOwner(String value) {
        return new JAXBElement<String>(_Owner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "elem")
    public JAXBElement<String> createElem(String value) {
        return new JAXBElement<String>(_Elem_QNAME, String.class, null, value);
    }

}
