//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 04:17:54 PM MSK
//

package io.rsug.zatupka.xiobj;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.rsug.zatupka.xiobj package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Elem_QNAME = new QName("urn:sap-com:xi", "elem");
    private static final QName _ModifBy_QNAME = new QName("urn:sap-com:xi", "modifBy");
    private static final QName _ModifAt_QNAME = new QName("urn:sap-com:xi", "modifAt");
    private static final QName _Owner_QNAME = new QName("urn:sap-com:xi", "owner");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.rsug.zatupka.xiobj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XiObj }
     * 
     * @return
     *     the new instance of {@link XiObj }
     */
    public XiObj createXiObj() {
        return new XiObj();
    }

    /**
     * Create an instance of {@link IdInfo }
     * 
     * @return
     *     the new instance of {@link IdInfo }
     */
    public IdInfo createIdInfo() {
        return new IdInfo();
    }

    /**
     * Create an instance of {@link Vc }
     * 
     * @return
     *     the new instance of {@link Vc }
     */
    public Vc createVc() {
        return new Vc();
    }

    /**
     * Create an instance of {@link ClCxt }
     * 
     * @return
     *     the new instance of {@link ClCxt }
     */
    public ClCxt createClCxt() {
        return new ClCxt();
    }

    /**
     * Create an instance of {@link Key }
     * 
     * @return
     *     the new instance of {@link Key }
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link Generic }
     * 
     * @return
     *     the new instance of {@link Generic }
     */
    public Generic createGeneric() {
        return new Generic();
    }

    /**
     * Create an instance of {@link AdmInf }
     * 
     * @return
     *     the new instance of {@link AdmInf }
     */
    public AdmInf createAdmInf() {
        return new AdmInf();
    }

    /**
     * Create an instance of {@link Lnks }
     * 
     * @return
     *     the new instance of {@link Lnks }
     */
    public Lnks createLnks() {
        return new Lnks();
    }

    /**
     * Create an instance of {@link LnkRole }
     * 
     * @return
     *     the new instance of {@link LnkRole }
     */
    public LnkRole createLnkRole() {
        return new LnkRole();
    }

    /**
     * Create an instance of {@link Lnk }
     * 
     * @return
     *     the new instance of {@link Lnk }
     */
    public Lnk createLnk() {
        return new Lnk();
    }

    /**
     * Create an instance of {@link TextInfo }
     * 
     * @return
     *     the new instance of {@link TextInfo }
     */
    public TextInfo createTextInfo() {
        return new TextInfo();
    }

    /**
     * Create an instance of {@link TextObj }
     * 
     * @return
     *     the new instance of {@link TextObj }
     */
    public TextObj createTextObj() {
        return new TextObj();
    }

    /**
     * Create an instance of {@link Texts }
     * 
     * @return
     *     the new instance of {@link Texts }
     */
    public Texts createTexts() {
        return new Texts();
    }

    /**
     * Create an instance of {@link Text }
     * 
     * @return
     *     the new instance of {@link Text }
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Inner }
     * 
     * @return
     *     the new instance of {@link Inner }
     */
    public Inner createInner() {
        return new Inner();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "elem")
    public JAXBElement<String> createElem(String value) {
        return new JAXBElement<>(_Elem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "modifBy")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createModifBy(String value) {
        return new JAXBElement<>(_ModifBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "modifAt")
    public JAXBElement<String> createModifAt(String value) {
        return new JAXBElement<>(_ModifAt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi", name = "owner")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOwner(String value) {
        return new JAXBElement<>(_Owner_QNAME, String.class, null, value);
    }

}
