//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:17:37 PM MSK
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:sap-com:xi", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.rsug.zatupka.xiobj;
