//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.07 at 07:59:06 PM MSK 
//


package io.rsug.zatupka.xiobj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:sap-com:xi}textObj"/>
 *       &lt;/sequence>
 *       &lt;attribute name="loadedL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textObj"
})
@XmlRootElement(name = "textInfo")
public class TextInfo {

    @XmlElement(required = true)
    protected TextObj textObj;
    @XmlAttribute(name = "loadedL", required = true)
    protected String loadedL;

    /**
     * Gets the value of the textObj property.
     * 
     * @return
     *     possible object is
     *     {@link TextObj }
     *     
     */
    public TextObj getTextObj() {
        return textObj;
    }

    /**
     * Sets the value of the textObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextObj }
     *     
     */
    public void setTextObj(TextObj value) {
        this.textObj = value;
    }

    /**
     * Gets the value of the loadedL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadedL() {
        return loadedL;
    }

    /**
     * Sets the value of the loadedL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadedL(String value) {
        this.loadedL = value;
    }

}
