//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.24 at 01:17:37 PM MSK
//

package io.rsug.zatupka.xiobj;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi}textObj"/>
 *       </sequence>
 *       <attribute name="loadedL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textObj"
})
@XmlRootElement(name = "textInfo")
public class TextInfo {

    @XmlElement(required = true)
    protected TextObj textObj;
    @XmlAttribute(name = "loadedL")
    protected String loadedL;

    /**
     * Gets the value of the textObj property.
     * 
     * @return
     *     possible object is
     *     {@link TextObj }
     *     
     */
    public TextObj getTextObj() {
        return textObj;
    }

    /**
     * Sets the value of the textObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextObj }
     *     
     */
    public void setTextObj(TextObj value) {
        this.textObj = value;
    }

    /**
     * Gets the value of the loadedL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadedL() {
        return loadedL;
    }

    /**
     * Sets the value of the loadedL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadedL(String value) {
        this.loadedL = value;
    }

}
