//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.07 at 09:30:16 PM MSK 
//


package io.rsug.zatupka.xiobj;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:sap-com:xi}clCxt"/>
 *       &lt;/sequence>
 *       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="sp" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="swcGuid" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="vcType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clCxt"
})
@XmlRootElement(name = "vc")
public class Vc {

    @XmlElement(required = true)
    protected ClCxt clCxt;
    @XmlAttribute(name = "caption")
    @XmlSchemaType(name = "anySimpleType")
    protected String caption;
    @XmlAttribute(name = "sp")
    protected BigInteger sp;
    @XmlAttribute(name = "swcGuid")
    @XmlSchemaType(name = "anySimpleType")
    protected String swcGuid;
    @XmlAttribute(name = "vcType", required = true)
    protected String vcType;

    /**
     * Gets the value of the clCxt property.
     * 
     * @return
     *     possible object is
     *     {@link ClCxt }
     *     
     */
    public ClCxt getClCxt() {
        return clCxt;
    }

    /**
     * Sets the value of the clCxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClCxt }
     *     
     */
    public void setClCxt(ClCxt value) {
        this.clCxt = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the sp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSp() {
        return sp;
    }

    /**
     * Sets the value of the sp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSp(BigInteger value) {
        this.sp = value;
    }

    /**
     * Gets the value of the swcGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwcGuid() {
        return swcGuid;
    }

    /**
     * Sets the value of the swcGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwcGuid(String value) {
        this.swcGuid = value;
    }

    /**
     * Gets the value of the vcType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVcType() {
        return vcType;
    }

    /**
     * Sets the value of the vcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcType(String value) {
        this.vcType = value;
    }

}
