//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:50:18 PM MSK
//

package io.rsug.zatupka.dir;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi:xiChannel}EngineType"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}EngineName"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}ChannelDirection"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}MessageProtocol"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}MessageProtocolVersion"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}TransportProtocol"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}TransportProtocolVersion"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}FromPartyAgency"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}FromPartySchema"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}ToPartyAgency"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}ToPartySchema"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}ChannelAttributes"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}PipelineAttributes"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "engineType",
    "engineName",
    "channelDirection",
    "messageProtocol",
    "messageProtocolVersion",
    "transportProtocol",
    "transportProtocolVersion",
    "fromPartyAgency",
    "fromPartySchema",
    "toPartyAgency",
    "toPartySchema",
    "channelAttributes",
    "pipelineAttributes"
})
@XmlRootElement(name = "Channel")
public class Channel {

    @XmlElement(name = "EngineType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String engineType;
    @XmlElement(name = "EngineName", required = true)
    protected EngineName engineName;
    @XmlElement(name = "ChannelDirection", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String channelDirection;
    @XmlElement(name = "MessageProtocol", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String messageProtocol;
    @XmlElement(name = "MessageProtocolVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String messageProtocolVersion;
    @XmlElement(name = "TransportProtocol", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String transportProtocol;
    @XmlElement(name = "TransportProtocolVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String transportProtocolVersion;
    @XmlElement(name = "FromPartyAgency", required = true)
    protected FromPartyAgency fromPartyAgency;
    @XmlElement(name = "FromPartySchema", required = true)
    protected FromPartySchema fromPartySchema;
    @XmlElement(name = "ToPartyAgency", required = true)
    protected ToPartyAgency toPartyAgency;
    @XmlElement(name = "ToPartySchema", required = true)
    protected ToPartySchema toPartySchema;
    @XmlElement(name = "ChannelAttributes", required = true)
    protected ChannelAttributes channelAttributes;
    @XmlElement(name = "PipelineAttributes", required = true)
    protected PipelineAttributes pipelineAttributes;

    /**
     * Gets the value of the engineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineType() {
        return engineType;
    }

    /**
     * Sets the value of the engineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineType(String value) {
        this.engineType = value;
    }

    /**
     * Gets the value of the engineName property.
     * 
     * @return
     *     possible object is
     *     {@link EngineName }
     *     
     */
    public EngineName getEngineName() {
        return engineName;
    }

    /**
     * Sets the value of the engineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link EngineName }
     *     
     */
    public void setEngineName(EngineName value) {
        this.engineName = value;
    }

    /**
     * Gets the value of the channelDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelDirection() {
        return channelDirection;
    }

    /**
     * Sets the value of the channelDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelDirection(String value) {
        this.channelDirection = value;
    }

    /**
     * Gets the value of the messageProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageProtocol() {
        return messageProtocol;
    }

    /**
     * Sets the value of the messageProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageProtocol(String value) {
        this.messageProtocol = value;
    }

    /**
     * Gets the value of the messageProtocolVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageProtocolVersion() {
        return messageProtocolVersion;
    }

    /**
     * Sets the value of the messageProtocolVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageProtocolVersion(String value) {
        this.messageProtocolVersion = value;
    }

    /**
     * Gets the value of the transportProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportProtocol() {
        return transportProtocol;
    }

    /**
     * Sets the value of the transportProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportProtocol(String value) {
        this.transportProtocol = value;
    }

    /**
     * Gets the value of the transportProtocolVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportProtocolVersion() {
        return transportProtocolVersion;
    }

    /**
     * Sets the value of the transportProtocolVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportProtocolVersion(String value) {
        this.transportProtocolVersion = value;
    }

    /**
     * Gets the value of the fromPartyAgency property.
     * 
     * @return
     *     possible object is
     *     {@link FromPartyAgency }
     *     
     */
    public FromPartyAgency getFromPartyAgency() {
        return fromPartyAgency;
    }

    /**
     * Sets the value of the fromPartyAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromPartyAgency }
     *     
     */
    public void setFromPartyAgency(FromPartyAgency value) {
        this.fromPartyAgency = value;
    }

    /**
     * Gets the value of the fromPartySchema property.
     * 
     * @return
     *     possible object is
     *     {@link FromPartySchema }
     *     
     */
    public FromPartySchema getFromPartySchema() {
        return fromPartySchema;
    }

    /**
     * Sets the value of the fromPartySchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromPartySchema }
     *     
     */
    public void setFromPartySchema(FromPartySchema value) {
        this.fromPartySchema = value;
    }

    /**
     * Gets the value of the toPartyAgency property.
     * 
     * @return
     *     possible object is
     *     {@link ToPartyAgency }
     *     
     */
    public ToPartyAgency getToPartyAgency() {
        return toPartyAgency;
    }

    /**
     * Sets the value of the toPartyAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPartyAgency }
     *     
     */
    public void setToPartyAgency(ToPartyAgency value) {
        this.toPartyAgency = value;
    }

    /**
     * Gets the value of the toPartySchema property.
     * 
     * @return
     *     possible object is
     *     {@link ToPartySchema }
     *     
     */
    public ToPartySchema getToPartySchema() {
        return toPartySchema;
    }

    /**
     * Sets the value of the toPartySchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToPartySchema }
     *     
     */
    public void setToPartySchema(ToPartySchema value) {
        this.toPartySchema = value;
    }

    /**
     * Gets the value of the channelAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ChannelAttributes }
     *     
     */
    public ChannelAttributes getChannelAttributes() {
        return channelAttributes;
    }

    /**
     * Sets the value of the channelAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChannelAttributes }
     *     
     */
    public void setChannelAttributes(ChannelAttributes value) {
        this.channelAttributes = value;
    }

    /**
     * Gets the value of the pipelineAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link PipelineAttributes }
     *     
     */
    public PipelineAttributes getPipelineAttributes() {
        return pipelineAttributes;
    }

    /**
     * Sets the value of the pipelineAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PipelineAttributes }
     *     
     */
    public void setPipelineAttributes(PipelineAttributes value) {
        this.pipelineAttributes = value;
    }
}
