//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 07:22:22 PM MSK
//

package io.rsug.zatupka.dir;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.rsug.zatupka.dir package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Agency_QNAME = new QName("urn:sap-com:xi:xiParty", "Agency");
    private static final QName _Schema_QNAME = new QName("urn:sap-com:xi:xiParty", "Schema");
    private static final QName _Identifier_QNAME = new QName("urn:sap-com:xi:xiParty", "Identifier");
    private static final QName _ServiceType_QNAME = new QName("urn:sap-com:xi:xiService", "ServiceType");
    private static final QName _IsThirdParty_QNAME = new QName("urn:sap-com:xi:xiService", "IsThirdParty");
    private static final QName _IsNWBPMProcess_QNAME = new QName("urn:sap-com:xi:xiService", "isNWBPMProcess");
    private static final QName _EngineType_QNAME = new QName("urn:sap-com:xi:xiChannel", "EngineType");
    private static final QName _ChannelDirection_QNAME = new QName("urn:sap-com:xi:xiChannel", "ChannelDirection");
    private static final QName _MessageProtocol_QNAME = new QName("urn:sap-com:xi:xiChannel", "MessageProtocol");
    private static final QName _MessageProtocolVersion_QNAME = new QName("urn:sap-com:xi:xiChannel", "MessageProtocolVersion");
    private static final QName _TransportProtocol_QNAME = new QName("urn:sap-com:xi:xiChannel", "TransportProtocol");
    private static final QName _TransportProtocolVersion_QNAME = new QName("urn:sap-com:xi:xiChannel", "TransportProtocolVersion");
    private static final QName _Position_QNAME = new QName("urn:sap-com:xi:xiChannel", "Position");
    private static final QName _ModuleName_QNAME = new QName("urn:sap-com:xi:xiChannel", "ModuleName");
    private static final QName _ModuleType_QNAME = new QName("urn:sap-com:xi:xiChannel", "ModuleType");
    private static final QName _ModuleNs_QNAME = new QName("urn:sap-com:xi:xiChannel", "ModuleNs");
    private static final QName _ParamName_QNAME = new QName("urn:sap-com:xi:xiChannel", "ParamName");
    private static final QName _ParamValue_QNAME = new QName("urn:sap-com:xi:xiChannel", "ParamValue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.rsug.zatupka.dir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChannelAttributes }
     * 
     * @return
     *     the new instance of {@link ChannelAttributes }
     */
    public ChannelAttributes createChannelAttributes() {
        return new ChannelAttributes();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData }
     * 
     * @return
     *     the new instance of {@link ChannelAttributes.AdapterTypeData }
     */
    public ChannelAttributes.AdapterTypeData createChannelAttributesAdapterTypeData() {
        return new ChannelAttributes.AdapterTypeData();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData.Attribute }
     * 
     * @return
     *     the new instance of {@link ChannelAttributes.AdapterTypeData.Attribute }
     */
    public ChannelAttributes.AdapterTypeData.Attribute createChannelAttributesAdapterTypeDataAttribute() {
        return new ChannelAttributes.AdapterTypeData.Attribute();
    }

    /**
     * Create an instance of {@link Party }
     * 
     * @return
     *     the new instance of {@link Party }
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link PartyIdentifier }
     * 
     * @return
     *     the new instance of {@link PartyIdentifier }
     */
    public PartyIdentifier createPartyIdentifier() {
        return new PartyIdentifier();
    }

    /**
     * Create an instance of {@link Service }
     * 
     * @return
     *     the new instance of {@link Service }
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     * @return
     *     the new instance of {@link Channel }
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link EngineName }
     * 
     * @return
     *     the new instance of {@link EngineName }
     */
    public EngineName createEngineName() {
        return new EngineName();
    }

    /**
     * Create an instance of {@link FromPartyAgency }
     * 
     * @return
     *     the new instance of {@link FromPartyAgency }
     */
    public FromPartyAgency createFromPartyAgency() {
        return new FromPartyAgency();
    }

    /**
     * Create an instance of {@link FromPartySchema }
     * 
     * @return
     *     the new instance of {@link FromPartySchema }
     */
    public FromPartySchema createFromPartySchema() {
        return new FromPartySchema();
    }

    /**
     * Create an instance of {@link ToPartyAgency }
     * 
     * @return
     *     the new instance of {@link ToPartyAgency }
     */
    public ToPartyAgency createToPartyAgency() {
        return new ToPartyAgency();
    }

    /**
     * Create an instance of {@link ToPartySchema }
     * 
     * @return
     *     the new instance of {@link ToPartySchema }
     */
    public ToPartySchema createToPartySchema() {
        return new ToPartySchema();
    }

    /**
     * Create an instance of {@link PipelineAttributes }
     * 
     * @return
     *     the new instance of {@link PipelineAttributes }
     */
    public PipelineAttributes createPipelineAttributes() {
        return new PipelineAttributes();
    }

    /**
     * Create an instance of {@link PipelineData }
     * 
     * @return
     *     the new instance of {@link PipelineData }
     */
    public PipelineData createPipelineData() {
        return new PipelineData();
    }

    /**
     * Create an instance of {@link PipelineConfig }
     * 
     * @return
     *     the new instance of {@link PipelineConfig }
     */
    public PipelineConfig createPipelineConfig() {
        return new PipelineConfig();
    }

    /**
     * Create an instance of {@link ModuleData }
     * 
     * @return
     *     the new instance of {@link ModuleData }
     */
    public ModuleData createModuleData() {
        return new ModuleData();
    }

    /**
     * Create an instance of {@link ModuleConfig }
     * 
     * @return
     *     the new instance of {@link ModuleConfig }
     */
    public ModuleConfig createModuleConfig() {
        return new ModuleConfig();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData.Attribute.Namespace }
     * 
     * @return
     *     the new instance of {@link ChannelAttributes.AdapterTypeData.Attribute.Namespace }
     */
    public ChannelAttributes.AdapterTypeData.Attribute.Namespace createChannelAttributesAdapterTypeDataAttributeNamespace() {
        return new ChannelAttributes.AdapterTypeData.Attribute.Namespace();
    }

    /**
     * Create an instance of {@link ChannelAttributes.AdapterTypeData.Attribute.Value }
     * 
     * @return
     *     the new instance of {@link ChannelAttributes.AdapterTypeData.Attribute.Value }
     */
    public ChannelAttributes.AdapterTypeData.Attribute.Value createChannelAttributesAdapterTypeDataAttributeValue() {
        return new ChannelAttributes.AdapterTypeData.Attribute.Value();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiParty", name = "Agency")
    public JAXBElement<String> createAgency(String value) {
        return new JAXBElement<>(_Agency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiParty", name = "Schema")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSchema(String value) {
        return new JAXBElement<>(_Schema_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiParty", name = "Identifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIdentifier(String value) {
        return new JAXBElement<>(_Identifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiService", name = "ServiceType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createServiceType(String value) {
        return new JAXBElement<>(_ServiceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiService", name = "IsThirdParty")
    public JAXBElement<Boolean> createIsThirdParty(Boolean value) {
        return new JAXBElement<>(_IsThirdParty_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiService", name = "isNWBPMProcess")
    public JAXBElement<Boolean> createIsNWBPMProcess(Boolean value) {
        return new JAXBElement<>(_IsNWBPMProcess_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "EngineType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEngineType(String value) {
        return new JAXBElement<>(_EngineType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ChannelDirection")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createChannelDirection(String value) {
        return new JAXBElement<>(_ChannelDirection_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "MessageProtocol")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMessageProtocol(String value) {
        return new JAXBElement<>(_MessageProtocol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "MessageProtocolVersion")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMessageProtocolVersion(String value) {
        return new JAXBElement<>(_MessageProtocolVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "TransportProtocol")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransportProtocol(String value) {
        return new JAXBElement<>(_TransportProtocol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "TransportProtocolVersion")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransportProtocolVersion(String value) {
        return new JAXBElement<>(_TransportProtocolVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "Position")
    @XmlJavaTypeAdapter(Adapter1 .class)
    public JAXBElement<Integer> createPosition(Integer value) {
        return new JAXBElement<>(_Position_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ModuleName")
    public JAXBElement<String> createModuleName(String value) {
        return new JAXBElement<>(_ModuleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ModuleType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createModuleType(String value) {
        return new JAXBElement<>(_ModuleType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ModuleNs")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createModuleNs(String value) {
        return new JAXBElement<>(_ModuleNs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ParamName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParamName(String value) {
        return new JAXBElement<>(_ParamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:sap-com:xi:xiChannel", name = "ParamValue")
    public JAXBElement<String> createParamValue(String value) {
        return new JAXBElement<>(_ParamValue_QNAME, String.class, null, value);
    }

}
