//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:50:18 PM MSK
//

package io.rsug.zatupka.dir;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi:xiChannel}PipelineData"/>
 *         <element ref="{urn:sap-com:xi:xiChannel}ModuleData"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pipelineData",
    "moduleData"
})
@XmlRootElement(name = "PipelineAttributes")
public class PipelineAttributes {

    @XmlElement(name = "PipelineData", required = true)
    protected PipelineData pipelineData;
    @XmlElement(name = "ModuleData", required = true)
    protected ModuleData moduleData;

    /**
     * Gets the value of the pipelineData property.
     * 
     * @return
     *     possible object is
     *     {@link PipelineData }
     *     
     */
    public PipelineData getPipelineData() {
        return pipelineData;
    }

    /**
     * Sets the value of the pipelineData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PipelineData }
     *     
     */
    public void setPipelineData(PipelineData value) {
        this.pipelineData = value;
    }

    /**
     * Gets the value of the moduleData property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleData }
     *     
     */
    public ModuleData getModuleData() {
        return moduleData;
    }

    /**
     * Sets the value of the moduleData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleData }
     *     
     */
    public void setModuleData(ModuleData value) {
        this.moduleData = value;
    }

}
