//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.07.23 at 04:50:18 PM MSK
//

package io.rsug.zatupka.dir;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:sap-com:xi:xiService}ServiceType"/>
 *         <element ref="{urn:sap-com:xi:xiService}IsThirdParty"/>
 *         <element ref="{urn:sap-com:xi:xiService}isNWBPMProcess"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceType",
    "isThirdParty",
    "isNWBPMProcess"
})
@XmlRootElement(name = "Service", namespace = "urn:sap-com:xi:xiService")
public class Service {

    @XmlElement(name = "ServiceType", namespace = "urn:sap-com:xi:xiService", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String serviceType;
    @XmlElement(name = "IsThirdParty", namespace = "urn:sap-com:xi:xiService")
    protected boolean isThirdParty;
    @XmlElement(namespace = "urn:sap-com:xi:xiService")
    protected boolean isNWBPMProcess;

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the isThirdParty property.
     * 
     */
    public boolean isIsThirdParty() {
        return isThirdParty;
    }

    /**
     * Sets the value of the isThirdParty property.
     * 
     */
    public void setIsThirdParty(boolean value) {
        this.isThirdParty = value;
    }

    /**
     * Gets the value of the isNWBPMProcess property.
     * 
     */
    public boolean isIsNWBPMProcess() {
        return isNWBPMProcess;
    }

    /**
     * Sets the value of the isNWBPMProcess property.
     * 
     */
    public void setIsNWBPMProcess(boolean value) {
        this.isNWBPMProcess = value;
    }

}
