//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.08 at 08:43:39 AM MSK 
//


package io.rsug.zatupka.dir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:sap-com:xi:xiService}ServiceType"/>
 *         &lt;element ref="{urn:sap-com:xi:xiService}IsThirdParty"/>
 *         &lt;element ref="{urn:sap-com:xi:xiService}isNWBPMProcess"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceType",
    "isThirdParty",
    "isNWBPMProcess"
})
@XmlRootElement(name = "Service", namespace = "urn:sap-com:xi:xiService")
public class Service {

    @XmlElement(name = "ServiceType", namespace = "urn:sap-com:xi:xiService", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String serviceType;
    @XmlElement(name = "IsThirdParty", namespace = "urn:sap-com:xi:xiService")
    protected boolean isThirdParty;
    @XmlElement(namespace = "urn:sap-com:xi:xiService")
    protected boolean isNWBPMProcess;

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the isThirdParty property.
     * 
     */
    public boolean isIsThirdParty() {
        return isThirdParty;
    }

    /**
     * Sets the value of the isThirdParty property.
     * 
     */
    public void setIsThirdParty(boolean value) {
        this.isThirdParty = value;
    }

    /**
     * Gets the value of the isNWBPMProcess property.
     * 
     */
    public boolean isIsNWBPMProcess() {
        return isNWBPMProcess;
    }

    /**
     * Sets the value of the isNWBPMProcess property.
     * 
     */
    public void setIsNWBPMProcess(boolean value) {
        this.isNWBPMProcess = value;
    }

}
